import { defineStrings } from './define';

/** Strings used across several restaurant screens. Area files hold the rest. */
export default defineStrings(
  {
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving...',
    close: 'Close',
    retry: 'Retry',
    error: 'Error',
    ok: 'OK',

    tabDashboard: 'Dashboard',
    tabOrders: 'Orders',
    tabMenu: 'Menu',
    tabProfile: 'Profile',

    statusPending: 'Pending',
    statusConfirmed: 'Confirmed',
    statusPreparing: 'Preparing',
    statusReady: 'Ready',
    statusPickedUp: 'Picked up',
    statusOutForDelivery: 'Out for delivery',
    statusDelivered: 'Delivered',
    statusCancelled: 'Cancelled',

    justNow: 'Just now',
    minutesAgo: '{count}m ago',
    hoursAgo: '{count}h ago',
    daysAgo: '{count}d ago',

    language: 'Language',
    languageHint: 'Applies to the restaurant app on this device',

    reviewsTitle: 'Reviews',
    recentReviews: 'Recent Reviews',
    reviewsNoun: 'reviews',
    reviewNoun: 'review',
    reviewsEmpty: 'No reviews yet. Customers can review dishes after their order is delivered.',
    back: 'Back',
    seeAll: 'See all',
    noReviews: 'No reviews yet',
    reviewsLoadFailed: 'Could not load reviews',
    dishRatingsNoun: 'dish ratings',
    dishRatingNoun: 'dish rating',
  },
  {
    ur: {
      cancel: 'منسوخ کریں',
      save: 'محفوظ کریں',
      saving: 'محفوظ ہو رہا ہے...',
      close: 'بند کریں',
      retry: 'دوبارہ کوشش کریں',
      error: 'خرابی',
      ok: 'ٹھیک ہے',

      tabDashboard: 'ڈیش بورڈ',
      tabOrders: 'آرڈرز',
      tabMenu: 'مینو',
      tabProfile: 'پروفائل',

      statusPending: 'زیرِ التوا',
      statusConfirmed: 'تصدیق شدہ',
      statusPreparing: 'تیار ہو رہا ہے',
      statusReady: 'تیار',
      statusPickedUp: 'اٹھا لیا گیا',
      statusOutForDelivery: 'ڈیلیوری کے لیے روانہ',
      statusDelivered: 'پہنچا دیا گیا',
      statusCancelled: 'منسوخ',

      justNow: 'ابھی ابھی',
      minutesAgo: '{count} منٹ پہلے',
      hoursAgo: '{count} گھنٹے پہلے',
      daysAgo: '{count} دن پہلے',

      language: 'زبان',
      languageHint: 'اس ڈیوائس پر ریسٹورنٹ ایپ پر لاگو ہوتی ہے',

      reviewsTitle: 'ریویوز',
      recentReviews: 'حالیہ ریویوز',
      reviewsNoun: 'ریویوز',
      reviewNoun: 'ریویو',
      reviewsEmpty: 'ابھی کوئی ریویو نہیں۔ آرڈر پہنچنے کے بعد گاہک کھانوں پر ریویو دے سکتے ہیں۔',
      back: 'واپس',
      seeAll: 'سب دیکھیں',
      noReviews: 'ابھی کوئی ریویو نہیں',
      reviewsLoadFailed: 'ریویوز لوڈ نہیں ہو سکے',
      dishRatingsNoun: 'کھانوں کی ریٹنگز',
      dishRatingNoun: 'کھانے کی ریٹنگ',
    },
    es: {
      cancel: 'Cancelar',
      save: 'Guardar',
      saving: 'Guardando...',
      close: 'Cerrar',
      retry: 'Reintentar',
      error: 'Error',
      ok: 'Aceptar',

      tabDashboard: 'Panel',
      tabOrders: 'Pedidos',
      tabMenu: 'Menú',
      tabProfile: 'Perfil',

      statusPending: 'Pendiente',
      statusConfirmed: 'Confirmado',
      statusPreparing: 'En preparación',
      statusReady: 'Listo',
      statusPickedUp: 'Recogido',
      statusOutForDelivery: 'En camino',
      statusDelivered: 'Entregado',
      statusCancelled: 'Cancelado',

      justNow: 'Ahora mismo',
      minutesAgo: 'hace {count} min',
      hoursAgo: 'hace {count} h',
      daysAgo: 'hace {count} d',

      language: 'Idioma',
      languageHint: 'Se aplica a la app del restaurante en este dispositivo',

      reviewsTitle: 'Reseñas',
      recentReviews: 'Reseñas recientes',
      reviewsNoun: 'reseñas',
      reviewNoun: 'reseña',
      reviewsEmpty: 'Aún no hay reseñas. Los clientes pueden reseñar platos cuando reciben su pedido.',
      back: 'Atrás',
      seeAll: 'Ver todo',
      noReviews: 'Aún no hay reseñas',
      reviewsLoadFailed: 'No se pudieron cargar las reseñas',
      dishRatingsNoun: 'valoraciones de platos',
      dishRatingNoun: 'valoración de plato',
    },
    fr: {
      cancel: 'Annuler',
      save: 'Enregistrer',
      saving: 'Enregistrement...',
      close: 'Fermer',
      retry: 'Réessayer',
      error: 'Erreur',
      ok: 'OK',

      tabDashboard: 'Tableau de bord',
      tabOrders: 'Commandes',
      tabMenu: 'Menu',
      tabProfile: 'Profil',

      statusPending: 'En attente',
      statusConfirmed: 'Confirmée',
      statusPreparing: 'En préparation',
      statusReady: 'Prête',
      statusPickedUp: 'Récupérée',
      statusOutForDelivery: 'En livraison',
      statusDelivered: 'Livrée',
      statusCancelled: 'Annulée',

      justNow: "À l'instant",
      minutesAgo: 'il y a {count} min',
      hoursAgo: 'il y a {count} h',
      daysAgo: 'il y a {count} j',

      language: 'Langue',
      languageHint: "S'applique à l'app restaurant sur cet appareil",

      reviewsTitle: 'Avis',
      recentReviews: 'Avis récents',
      reviewsNoun: 'avis',
      reviewNoun: 'avis',
      reviewsEmpty: "Pas encore d'avis. Les clients peuvent noter les plats une fois leur commande livrée.",
      back: 'Retour',
      seeAll: 'Tout voir',
      noReviews: "Pas encore d'avis",
      reviewsLoadFailed: 'Impossible de charger les avis',
      dishRatingsNoun: 'notes de plats',
      dishRatingNoun: 'note de plat',
    },
  },
);
