import { defineStrings } from './define';

/** Restaurant dashboard (kitchen overview) strings. */
export default defineStrings(
  {
    dashWelcomeBack: 'Welcome back',
    dashOpen: 'Open',
    dashClosed: 'Closed',
    dashOverview: 'Overview',
    dashOverviewNamed: '{name} Overview',
    dashTodaysRevenue: "Today's revenue",
    dashOrdersTodayOne: '{count} order today',
    dashOrdersTodayOther: '{count} orders today',
    dashRecentOrders: 'Recent Orders',
    dashNoRecentOrders: 'No recent orders',
    dashCustomer: 'Customer',
    dashItemsOne: '{count} item',
    dashItemsOther: '{count} items',
    dashGoodMorning: 'Good Morning',
    dashGoodAfternoon: 'Good Afternoon',
    dashGoodEvening: 'Good Evening',
  },
  {
    ur: {
      dashWelcomeBack: 'خوش آمدید',
      dashOpen: 'کھلا ہے',
      dashClosed: 'بند ہے',
      dashOverview: 'جائزہ',
      dashOverviewNamed: '{name} کا جائزہ',
      dashTodaysRevenue: 'آج کی آمدنی',
      dashOrdersTodayOne: 'آج {count} آرڈر',
      dashOrdersTodayOther: 'آج {count} آرڈرز',
      dashRecentOrders: 'حالیہ آرڈرز',
      dashNoRecentOrders: 'کوئی حالیہ آرڈر نہیں',
      dashCustomer: 'گاہک',
      dashItemsOne: '{count} آئٹم',
      dashItemsOther: '{count} آئٹمز',
      dashGoodMorning: 'صبح بخیر',
      dashGoodAfternoon: 'سہ پہر بخیر',
      dashGoodEvening: 'شام بخیر',
    },
    es: {
      dashWelcomeBack: 'Bienvenido de nuevo',
      dashOpen: 'Abierto',
      dashClosed: 'Cerrado',
      dashOverview: 'Resumen',
      dashOverviewNamed: 'Resumen de {name}',
      dashTodaysRevenue: 'Ingresos de hoy',
      dashOrdersTodayOne: '{count} pedido hoy',
      dashOrdersTodayOther: '{count} pedidos hoy',
      dashRecentOrders: 'Pedidos recientes',
      dashNoRecentOrders: 'No hay pedidos recientes',
      dashCustomer: 'Cliente',
      dashItemsOne: '{count} artículo',
      dashItemsOther: '{count} artículos',
      dashGoodMorning: 'Buenos días',
      dashGoodAfternoon: 'Buenas tardes',
      dashGoodEvening: 'Buenas noches',
    },
    fr: {
      dashWelcomeBack: 'Bon retour',
      dashOpen: 'Ouvert',
      dashClosed: 'Fermé',
      dashOverview: 'Aperçu',
      dashOverviewNamed: 'Aperçu de {name}',
      dashTodaysRevenue: "Chiffre d'affaires du jour",
      dashOrdersTodayOne: "{count} commande aujourd'hui",
      dashOrdersTodayOther: "{count} commandes aujourd'hui",
      dashRecentOrders: 'Commandes récentes',
      dashNoRecentOrders: 'Aucune commande récente',
      dashCustomer: 'Client',
      dashItemsOne: '{count} article',
      dashItemsOther: '{count} articles',
      dashGoodMorning: 'Bonjour',
      dashGoodAfternoon: 'Bon après-midi',
      dashGoodEvening: 'Bonsoir',
    },
  },
);
