import { defineStrings } from './define';

/** Menu tab: item list, category filter, add/edit item and add category modals. */
export default defineStrings(
  {
    menuTitle: 'Manage Menu Items',
    menuSubtitle: 'Manage your menu offerings and pricing',
    menuAddNewItem: 'ADD NEW ITEM',
    menuAllItems: 'All Items',
    menuAddCategoryA11y: 'Add category',
    menuAddItemA11y: 'Add menu item',
    menuEmptyTitle: 'No Menu Items',
    menuEmptySubtitle: 'Add your first menu item to get started.',

    menuDeleteTitle: 'Delete Item',
    menuDeleteConfirm: 'Are you sure you want to delete "{name}"?',
    menuDelete: 'Delete',
    menuAddCategoryFailed: 'Failed to add category',
    menuSaveItemFailed: 'Failed to save item',

    menuAddCategoryTitle: 'Add Category',
    menuCategoryNamePlaceholder: 'Category name',
    menuAdd: 'Add',

    menuTagVeg: 'VEG',
    menuTagVegan: 'VEGAN',
    menuTagGlutenFree: 'GF',
    menuTagUnavailable: 'UNAVAILABLE',
    menuPrepMinutes: '{count}m',
    menuCalories: '{count} cal',
    menuEdit: 'Edit',
    menuDeleteA11y: 'Delete item',

    menuSpiceMild: 'Mild',
    menuSpiceMedium: 'Medium',
    menuSpiceHot: 'Hot',
    menuSpiceExtraHot: 'Extra Hot',

    menuLimitReachedTitle: 'Limit Reached',
    menuLimitReachedMessage: 'You can only add up to 3 images per item',
    menuUploadFailedTitle: 'Upload Failed',
    menuUploadFailed: 'Failed to upload image',
    menuValidationTitle: 'Validation',
    menuValidationFields: 'Please fill in name, description, price, and category.',
    menuValidationImage: 'Please add at least one image for the menu item.',
    menuSaveMenuItemFailed: 'Failed to save menu item',

    menuEditItem: 'Edit Item',
    menuAddItem: 'Add Item',
    menuDishImages: 'DISH IMAGES',
    menuRemoveImageA11y: 'Remove image',
    menuAddImage: 'Add Image',
    menuTapToUpload: 'Tap to Upload Dish Image',
    menuImageHint: 'High-resolution JPG or PNG. Max 5MB.',
    menuProTip: 'Pro Tip',
    menuProTipBefore: 'Items with high-quality, bright photography see a ',
    menuProTipHighlight: '24% increase',
    menuProTipAfter: ' in orders.',
    menuItemDetails: 'ITEM DETAILS',
    menuItemName: 'ITEM NAME',
    menuItemNamePlaceholder: 'e.g. Truffle Infused Tagliatelle',
    menuPriceLabel: 'PRICE (RS.)',
    menuPrepTimeLabel: 'PREP TIME (min)',
    menuCategoryLabel: 'CATEGORY',
    menuDescriptionLabel: 'DESCRIPTION',
    menuDescriptionPlaceholder: 'Describe the flavors, ingredients, and preparation method...',
    menuSpiceLevelLabel: 'SPICE LEVEL',
    menuDietaryTags: 'DIETARY TAGS',
    menuVegetarian: 'Vegetarian',
    menuGlutenFree: 'Gluten-Free',
    menuVegan: 'Vegan',
    menuSaveItem: 'Save Item',
    menuCancelDiscard: 'Cancel & Discard Changes',
  },
  {
    ur: {
      menuTitle: 'مینو آئٹمز کا انتظام',
      menuSubtitle: 'اپنے مینو کے کھانے اور قیمتیں سنبھالیں',
      menuAddNewItem: 'نیا آئٹم شامل کریں',
      menuAllItems: 'تمام آئٹمز',
      menuAddCategoryA11y: 'کیٹیگری شامل کریں',
      menuAddItemA11y: 'مینو آئٹم شامل کریں',
      menuEmptyTitle: 'کوئی مینو آئٹم نہیں',
      menuEmptySubtitle: 'شروع کرنے کے لیے اپنا پہلا مینو آئٹم شامل کریں۔',

      menuDeleteTitle: 'آئٹم حذف کریں',
      menuDeleteConfirm: 'کیا آپ واقعی "{name}" حذف کرنا چاہتے ہیں؟',
      menuDelete: 'حذف کریں',
      menuAddCategoryFailed: 'کیٹیگری شامل نہیں ہو سکی',
      menuSaveItemFailed: 'آئٹم محفوظ نہیں ہو سکا',

      menuAddCategoryTitle: 'کیٹیگری شامل کریں',
      menuCategoryNamePlaceholder: 'کیٹیگری کا نام',
      menuAdd: 'شامل کریں',

      menuTagVeg: 'سبزی',
      menuTagVegan: 'ویگن',
      menuTagGlutenFree: 'گلوٹین فری',
      menuTagUnavailable: 'دستیاب نہیں',
      menuPrepMinutes: '{count} منٹ',
      menuCalories: '{count} کیلوریز',
      menuEdit: 'ترمیم',
      menuDeleteA11y: 'آئٹم حذف کریں',

      menuSpiceMild: 'ہلکا',
      menuSpiceMedium: 'درمیانہ',
      menuSpiceHot: 'تیز',
      menuSpiceExtraHot: 'بہت تیز',

      menuLimitReachedTitle: 'حد پوری ہو گئی',
      menuLimitReachedMessage: 'ہر آئٹم کے لیے زیادہ سے زیادہ 3 تصاویر شامل کی جا سکتی ہیں',
      menuUploadFailedTitle: 'اپ لوڈ ناکام',
      menuUploadFailed: 'تصویر اپ لوڈ نہیں ہو سکی',
      menuValidationTitle: 'معلومات نامکمل',
      menuValidationFields: 'براہِ کرم نام، تفصیل، قیمت اور کیٹیگری درج کریں۔',
      menuValidationImage: 'براہِ کرم مینو آئٹم کی کم از کم ایک تصویر شامل کریں۔',
      menuSaveMenuItemFailed: 'مینو آئٹم محفوظ نہیں ہو سکا',

      menuEditItem: 'آئٹم میں ترمیم',
      menuAddItem: 'آئٹم شامل کریں',
      menuDishImages: 'کھانے کی تصاویر',
      menuRemoveImageA11y: 'تصویر ہٹائیں',
      menuAddImage: 'تصویر شامل کریں',
      menuTapToUpload: 'کھانے کی تصویر اپ لوڈ کرنے کے لیے ٹیپ کریں',
      menuImageHint: 'اعلیٰ معیار کی JPG یا PNG، زیادہ سے زیادہ 5MB۔',
      menuProTip: 'مفید مشورہ',
      menuProTipBefore: 'اچھی اور روشن تصاویر والے آئٹمز کے آرڈرز میں ',
      menuProTipHighlight: '24% اضافہ',
      menuProTipAfter: ' ہوتا ہے۔',
      menuItemDetails: 'آئٹم کی تفصیلات',
      menuItemName: 'آئٹم کا نام',
      menuItemNamePlaceholder: 'مثلاً ٹرفل ٹیگلیاٹیلی',
      menuPriceLabel: 'قیمت (روپے)',
      menuPrepTimeLabel: 'تیاری کا وقت (منٹ)',
      menuCategoryLabel: 'کیٹیگری',
      menuDescriptionLabel: 'تفصیل',
      menuDescriptionPlaceholder: 'ذائقہ، اجزاء اور بنانے کا طریقہ بیان کریں...',
      menuSpiceLevelLabel: 'مرچ کی سطح',
      menuDietaryTags: 'غذائی ٹیگز',
      menuVegetarian: 'سبزی خور',
      menuGlutenFree: 'گلوٹین فری',
      menuVegan: 'ویگن',
      menuSaveItem: 'آئٹم محفوظ کریں',
      menuCancelDiscard: 'منسوخ کریں اور تبدیلیاں ختم کریں',
    },
    es: {
      menuTitle: 'Gestionar platos del menú',
      menuSubtitle: 'Gestiona la oferta y los precios de tu menú',
      menuAddNewItem: 'AÑADIR PLATO',
      menuAllItems: 'Todos',
      menuAddCategoryA11y: 'Añadir categoría',
      menuAddItemA11y: 'Añadir plato',
      menuEmptyTitle: 'Sin platos en el menú',
      menuEmptySubtitle: 'Añade tu primer plato para empezar.',

      menuDeleteTitle: 'Eliminar plato',
      menuDeleteConfirm: '¿Seguro que quieres eliminar "{name}"?',
      menuDelete: 'Eliminar',
      menuAddCategoryFailed: 'No se pudo añadir la categoría',
      menuSaveItemFailed: 'No se pudo guardar el plato',

      menuAddCategoryTitle: 'Añadir categoría',
      menuCategoryNamePlaceholder: 'Nombre de la categoría',
      menuAdd: 'Añadir',

      menuTagVeg: 'VEG',
      menuTagVegan: 'VEGANO',
      menuTagGlutenFree: 'SIN GLUTEN',
      menuTagUnavailable: 'NO DISPONIBLE',
      menuPrepMinutes: '{count} min',
      menuCalories: '{count} kcal',
      menuEdit: 'Editar',
      menuDeleteA11y: 'Eliminar plato',

      menuSpiceMild: 'Suave',
      menuSpiceMedium: 'Medio',
      menuSpiceHot: 'Picante',
      menuSpiceExtraHot: 'Muy picante',

      menuLimitReachedTitle: 'Límite alcanzado',
      menuLimitReachedMessage: 'Solo puedes añadir hasta 3 imágenes por plato',
      menuUploadFailedTitle: 'Error al subir',
      menuUploadFailed: 'No se pudo subir la imagen',
      menuValidationTitle: 'Faltan datos',
      menuValidationFields: 'Completa el nombre, la descripción, el precio y la categoría.',
      menuValidationImage: 'Añade al menos una imagen del plato.',
      menuSaveMenuItemFailed: 'No se pudo guardar el plato',

      menuEditItem: 'Editar plato',
      menuAddItem: 'Añadir plato',
      menuDishImages: 'IMÁGENES DEL PLATO',
      menuRemoveImageA11y: 'Quitar imagen',
      menuAddImage: 'Añadir imagen',
      menuTapToUpload: 'Toca para subir una imagen del plato',
      menuImageHint: 'JPG o PNG de alta resolución. Máx. 5 MB.',
      menuProTip: 'Consejo',
      menuProTipBefore: 'Los platos con fotos luminosas y de calidad tienen un ',
      menuProTipHighlight: '24% más',
      menuProTipAfter: ' de pedidos.',
      menuItemDetails: 'DETALLES DEL PLATO',
      menuItemName: 'NOMBRE DEL PLATO',
      menuItemNamePlaceholder: 'p. ej. Tagliatelle con trufa',
      menuPriceLabel: 'PRECIO (RS.)',
      menuPrepTimeLabel: 'PREPARACIÓN (min)',
      menuCategoryLabel: 'CATEGORÍA',
      menuDescriptionLabel: 'DESCRIPCIÓN',
      menuDescriptionPlaceholder: 'Describe los sabores, ingredientes y la preparación...',
      menuSpiceLevelLabel: 'NIVEL DE PICANTE',
      menuDietaryTags: 'ETIQUETAS DIETÉTICAS',
      menuVegetarian: 'Vegetariano',
      menuGlutenFree: 'Sin gluten',
      menuVegan: 'Vegano',
      menuSaveItem: 'Guardar plato',
      menuCancelDiscard: 'Cancelar y descartar cambios',
    },
    fr: {
      menuTitle: 'Gérer les plats du menu',
      menuSubtitle: 'Gérez vos plats et vos prix',
      menuAddNewItem: 'AJOUTER UN PLAT',
      menuAllItems: 'Tous',
      menuAddCategoryA11y: 'Ajouter une catégorie',
      menuAddItemA11y: 'Ajouter un plat',
      menuEmptyTitle: 'Aucun plat au menu',
      menuEmptySubtitle: 'Ajoutez votre premier plat pour commencer.',

      menuDeleteTitle: 'Supprimer le plat',
      menuDeleteConfirm: 'Voulez-vous vraiment supprimer « {name} » ?',
      menuDelete: 'Supprimer',
      menuAddCategoryFailed: "Impossible d'ajouter la catégorie",
      menuSaveItemFailed: "Impossible d'enregistrer le plat",

      menuAddCategoryTitle: 'Ajouter une catégorie',
      menuCategoryNamePlaceholder: 'Nom de la catégorie',
      menuAdd: 'Ajouter',

      menuTagVeg: 'VÉGÉ',
      menuTagVegan: 'VÉGAN',
      menuTagGlutenFree: 'SANS GLUTEN',
      menuTagUnavailable: 'INDISPONIBLE',
      menuPrepMinutes: '{count} min',
      menuCalories: '{count} kcal',
      menuEdit: 'Modifier',
      menuDeleteA11y: 'Supprimer le plat',

      menuSpiceMild: 'Doux',
      menuSpiceMedium: 'Moyen',
      menuSpiceHot: 'Épicé',
      menuSpiceExtraHot: 'Très épicé',

      menuLimitReachedTitle: 'Limite atteinte',
      menuLimitReachedMessage: "Vous pouvez ajouter jusqu'à 3 images par plat",
      menuUploadFailedTitle: "Échec de l'envoi",
      menuUploadFailed: "Impossible d'envoyer l'image",
      menuValidationTitle: 'Champs manquants',
      menuValidationFields: 'Renseignez le nom, la description, le prix et la catégorie.',
      menuValidationImage: 'Ajoutez au moins une image du plat.',
      menuSaveMenuItemFailed: "Impossible d'enregistrer le plat",

      menuEditItem: 'Modifier le plat',
      menuAddItem: 'Ajouter un plat',
      menuDishImages: 'IMAGES DU PLAT',
      menuRemoveImageA11y: "Retirer l'image",
      menuAddImage: 'Ajouter une image',
      menuTapToUpload: 'Touchez pour ajouter une photo du plat',
      menuImageHint: 'JPG ou PNG haute résolution. 5 Mo max.',
      menuProTip: 'Astuce',
      menuProTipBefore: 'Les plats avec des photos lumineuses et de qualité obtiennent ',
      menuProTipHighlight: '24 % de commandes',
      menuProTipAfter: ' en plus.',
      menuItemDetails: 'DÉTAILS DU PLAT',
      menuItemName: 'NOM DU PLAT',
      menuItemNamePlaceholder: 'ex. Tagliatelles à la truffe',
      menuPriceLabel: 'PRIX (RS.)',
      menuPrepTimeLabel: 'PRÉPARATION (min)',
      menuCategoryLabel: 'CATÉGORIE',
      menuDescriptionLabel: 'DESCRIPTION',
      menuDescriptionPlaceholder: 'Décrivez les saveurs, les ingrédients et la préparation...',
      menuSpiceLevelLabel: 'NIVEAU DE PIMENT',
      menuDietaryTags: 'RÉGIME ALIMENTAIRE',
      menuVegetarian: 'Végétarien',
      menuGlutenFree: 'Sans gluten',
      menuVegan: 'Végan',
      menuSaveItem: 'Enregistrer le plat',
      menuCancelDiscard: 'Annuler et abandonner',
    },
  },
);
