import { defineStrings } from './define';

/** Orders tab: list, filters, order card and order detail sheet. */
export default defineStrings(
  {
    ordersPageTitle: 'View All Orders',
    ordersPipelineTitle: 'Order Pipeline',
    ordersStatActive: 'ACTIVE ORDERS',
    ordersStatPreparing: 'IN PREPARATION',
    ordersStatReady: 'READY FOR PICKUP',
    ordersFilterAll: 'All',
    ordersCompleted: 'Completed',

    ordersEmptyTitle: 'No Orders Found',
    ordersEmptyAll: 'Orders will appear here when customers place them.',
    ordersEmptyFiltered: 'No {status} orders right now.',

    ordersUpdateFailed: 'Failed to update order status',
    ordersDeclineTitle: 'Decline Order',
    ordersDeclineMessage: 'Are you sure you want to decline this order?',
    ordersDeclineNo: 'No',
    ordersDeclineYes: 'Yes, Decline',
    ordersDecline: 'Decline',
    ordersAccept: 'Accept Order',
    ordersStartPreparing: 'Start Preparing',
    ordersMarkReady: 'Mark Ready',

    ordersCardItemsOne: '{count} Item',
    ordersCardItemsOther: '{count} Items',
    ordersCustomerFallback: 'Customer',

    ordersDetailTitle: 'Order #{number}',
    ordersDetailStatus: 'STATUS',
    ordersDetailItems: 'ORDER ITEMS',
    ordersDetailItemCountOne: '{count} ITEM',
    ordersDetailItemCountOther: '{count} ITEMS',
    ordersDetailQty: 'QTY: {count}',
    ordersDetailSubtotal: 'Subtotal',
    ordersDetailDeliveryFee: 'Delivery Fee',
    ordersDetailTax: 'Tax',
    ordersDetailTotal: 'TOTAL',
    ordersDetailCustomer: 'CUSTOMER',
    ordersDetailAddress: 'DELIVERY ADDRESS',
    ordersDetailDriverNote: 'DRIVER NOTE',
    ordersRiderLabel: 'RIDER',
    ordersRiderWaiting: 'Waiting for a rider',
    ordersRiderCall: 'Call rider',
  },
  {
    ur: {
      ordersPageTitle: 'تمام آرڈرز',
      ordersPipelineTitle: 'آرڈرز کی ترتیب',
      ordersStatActive: 'فعال آرڈرز',
      ordersStatPreparing: 'تیاری میں',
      ordersStatReady: 'پک اپ کے لیے تیار',
      ordersFilterAll: 'سب',
      ordersCompleted: 'مکمل',

      ordersEmptyTitle: 'کوئی آرڈر نہیں ملا',
      ordersEmptyAll: 'گاہک جب آرڈر دیں گے تو وہ یہاں نظر آئیں گے۔',
      ordersEmptyFiltered: 'اس وقت کوئی "{status}" آرڈر نہیں۔',

      ordersUpdateFailed: 'آرڈر کی حالت اپ ڈیٹ نہیں ہو سکی',
      ordersDeclineTitle: 'آرڈر مسترد کریں',
      ordersDeclineMessage: 'کیا آپ واقعی یہ آرڈر مسترد کرنا چاہتے ہیں؟',
      ordersDeclineNo: 'نہیں',
      ordersDeclineYes: 'ہاں، مسترد کریں',
      ordersDecline: 'مسترد کریں',
      ordersAccept: 'آرڈر قبول کریں',
      ordersStartPreparing: 'تیاری شروع کریں',
      ordersMarkReady: 'تیار ہے',

      ordersCardItemsOne: '{count} آئٹم',
      ordersCardItemsOther: '{count} آئٹمز',
      ordersCustomerFallback: 'گاہک',

      ordersDetailTitle: 'آرڈر #{number}',
      ordersDetailStatus: 'حالت',
      ordersDetailItems: 'آرڈر کی اشیاء',
      ordersDetailItemCountOne: '{count} آئٹم',
      ordersDetailItemCountOther: '{count} آئٹمز',
      ordersDetailQty: 'تعداد: {count}',
      ordersDetailSubtotal: 'ذیلی کل',
      ordersDetailDeliveryFee: 'ڈیلیوری فیس',
      ordersDetailTax: 'ٹیکس',
      ordersDetailTotal: 'کل',
      ordersDetailCustomer: 'گاہک',
      ordersDetailAddress: 'ڈیلیوری کا پتہ',
      ordersDetailDriverNote: 'رائیڈر کے لیے ہدایت',
      ordersRiderLabel: 'رائیڈر',
      ordersRiderWaiting: 'رائیڈر کا انتظار ہے',
      ordersRiderCall: 'رائیڈر کو کال کریں',
    },
    es: {
      ordersPageTitle: 'Todos los pedidos',
      ordersPipelineTitle: 'Flujo de pedidos',
      ordersStatActive: 'PEDIDOS ACTIVOS',
      ordersStatPreparing: 'EN PREPARACIÓN',
      ordersStatReady: 'LISTOS PARA RECOGER',
      ordersFilterAll: 'Todos',
      ordersCompleted: 'Completado',

      ordersEmptyTitle: 'No hay pedidos',
      ordersEmptyAll: 'Los pedidos aparecerán aquí cuando los clientes los hagan.',
      ordersEmptyFiltered: 'No hay pedidos «{status}» ahora mismo.',

      ordersUpdateFailed: 'No se pudo actualizar el estado del pedido',
      ordersDeclineTitle: 'Rechazar pedido',
      ordersDeclineMessage: '¿Seguro que quieres rechazar este pedido?',
      ordersDeclineNo: 'No',
      ordersDeclineYes: 'Sí, rechazar',
      ordersDecline: 'Rechazar',
      ordersAccept: 'Aceptar pedido',
      ordersStartPreparing: 'Empezar a preparar',
      ordersMarkReady: 'Marcar listo',

      ordersCardItemsOne: '{count} artículo',
      ordersCardItemsOther: '{count} artículos',
      ordersCustomerFallback: 'Cliente',

      ordersDetailTitle: 'Pedido #{number}',
      ordersDetailStatus: 'ESTADO',
      ordersDetailItems: 'ARTÍCULOS DEL PEDIDO',
      ordersDetailItemCountOne: '{count} ARTÍCULO',
      ordersDetailItemCountOther: '{count} ARTÍCULOS',
      ordersDetailQty: 'CANT.: {count}',
      ordersDetailSubtotal: 'Subtotal',
      ordersDetailDeliveryFee: 'Gastos de envío',
      ordersDetailTax: 'Impuestos',
      ordersDetailTotal: 'TOTAL',
      ordersDetailCustomer: 'CLIENTE',
      ordersDetailAddress: 'DIRECCIÓN DE ENTREGA',
      ordersDetailDriverNote: 'NOTA PARA EL REPARTIDOR',
      ordersRiderLabel: 'REPARTIDOR',
      ordersRiderWaiting: 'Esperando repartidor',
      ordersRiderCall: 'Llamar al repartidor',
    },
    fr: {
      ordersPageTitle: 'Toutes les commandes',
      ordersPipelineTitle: 'Suivi des commandes',
      ordersStatActive: 'COMMANDES ACTIVES',
      ordersStatPreparing: 'EN PRÉPARATION',
      ordersStatReady: 'PRÊTES À RETIRER',
      ordersFilterAll: 'Toutes',
      ordersCompleted: 'Terminée',

      ordersEmptyTitle: 'Aucune commande',
      ordersEmptyAll: 'Les commandes apparaîtront ici dès que les clients commanderont.',
      ordersEmptyFiltered: 'Aucune commande « {status} » pour le moment.',

      ordersUpdateFailed: 'Impossible de mettre à jour le statut de la commande',
      ordersDeclineTitle: 'Refuser la commande',
      ordersDeclineMessage: 'Voulez-vous vraiment refuser cette commande ?',
      ordersDeclineNo: 'Non',
      ordersDeclineYes: 'Oui, refuser',
      ordersDecline: 'Refuser',
      ordersAccept: 'Accepter',
      ordersStartPreparing: 'Lancer la préparation',
      ordersMarkReady: 'Marquer prête',

      ordersCardItemsOne: '{count} article',
      ordersCardItemsOther: '{count} articles',
      ordersCustomerFallback: 'Client',

      ordersDetailTitle: 'Commande n°{number}',
      ordersDetailStatus: 'STATUT',
      ordersDetailItems: 'ARTICLES',
      ordersDetailItemCountOne: '{count} ARTICLE',
      ordersDetailItemCountOther: '{count} ARTICLES',
      ordersDetailQty: 'QTÉ : {count}',
      ordersDetailSubtotal: 'Sous-total',
      ordersDetailDeliveryFee: 'Frais de livraison',
      ordersDetailTax: 'Taxes',
      ordersDetailTotal: 'TOTAL',
      ordersDetailCustomer: 'CLIENT',
      ordersDetailAddress: 'ADRESSE DE LIVRAISON',
      ordersDetailDriverNote: 'NOTE POUR LE LIVREUR',
      ordersRiderLabel: 'LIVREUR',
      ordersRiderWaiting: 'En attente d’un livreur',
      ordersRiderCall: 'Appeler le livreur',
    },
  },
);
