import { defineStrings } from './define';

/** Payouts & Billing sheet, payout detail and payout account form. */
export default defineStrings(
  {
    payoutsTitle: 'Payouts & Billing',
    payoutsAccountSection: 'Payout account',
    payoutsHowItWorks: 'How payouts work',
    payoutsInfoCommission: "Foodie's commission is {rate} of each order's food subtotal.",
    payoutsInfoFee: 'Online orders have a {rate} payment processing fee.',
    payoutsInfoCash: 'For cash orders you keep the cash, so their commission is taken from your online earnings.',
    payoutsInfoDelivery: "Delivery fees and rider tips aren't part of your payout.",
    payoutsHistory: 'Payout history',
    payoutsHistoryEmpty:
      'No payouts yet. Delivered orders are settled into a payout periodically, and each one will appear here.',
    payoutsOrderCount: '{count} orders',
    payoutsOrderCountOne: '1 order',
    payoutsShowOlder: 'Show older payouts',

    payoutsYouOwe: 'You owe Foodie',
    payoutsFoodiePaysYou: 'Foodie pays you',
    payoutsUpcoming: 'Upcoming earnings',
    payoutsNoUnsettled: 'No delivered orders waiting to be settled',
    payoutsUnsettledFrom: 'From {count} delivered orders not yet in a payout',
    payoutsUnsettledFromOne: 'From 1 delivered order not yet in a payout',
    payoutsSeeBreakdown: 'See breakdown',
    payoutsHideBreakdown: 'Hide breakdown',
    payoutsProcessingCount: 'Processing ({count} payouts)',
    payoutsProcessingCountOne: 'Processing (1 payout)',
    payoutsLastPayout: 'Last payout',

    payoutsAddAccountPrompt:
      "Add a bank account or mobile wallet so Foodie can send your earnings. Payouts can't be sent until one is added and verified.",
    payoutsAddAccount: 'Add payout account',
    payoutsEditAccount: 'Edit payout account',
    payoutsChangeAccount: 'Change payout account',
    payoutsVerifying: 'Foodie is verifying these details. Payouts are sent once they are verified.',
    payoutsRejected: "Foodie couldn't verify this account. Update the details to try again.",
    payoutsRejectedReason: "Foodie couldn't verify this account: {reason} Update the details to try again.",

    payoutsDetailTitle: 'Payout',
    payoutsReceived: 'Received',
    payoutsSent: 'Sent',
    payoutsReceivedOn: 'Received {date}',
    payoutsSentOn: 'Sent {date}',
    payoutsRef: 'Ref {reference}',
    payoutsFailedNote:
      "This transfer didn't go through. Check that your payout account details are correct; Foodie will send it again.",
    payoutsCollectNote: 'Foodie will contact you to collect this amount.',
    payoutsProcessingNote: 'Foodie is processing this payout to your account.',
    payoutsOrdersInPayout: 'Orders in this payout',
    payoutsCash: 'Cash',
    payoutsOnline: 'Online',

    payoutsStatusProcessing: 'Processing',
    payoutsStatusPending: 'Pending',
    payoutsStatusPaid: 'Paid',
    payoutsStatusVerified: 'Verified',
    payoutsStatusFailed: 'Failed',
    payoutsStatusRejected: 'Rejected',
    payoutsStatusNone: 'No account',

    payoutsOnlineSales: 'Online sales',
    payoutsCashSales: 'Cash sales (already with you)',
    payoutsCommission: 'Commission ({rate} of {gross})',
    payoutsPaymentFees: 'Online payment fees',

    payoutsFormIntro:
      'Foodie sends your earnings here. After you save, Foodie verifies the details before the next payout.',
    payoutsReceiveBy: 'Receive payouts by',
    payoutsAccountTitle: 'Account title',
    payoutsAccountTitlePlaceholderBank: 'e.g. Beef House Pvt Ltd',
    payoutsAccountTitlePlaceholderWallet: 'Name registered on the wallet',
    payoutsAccountTitleHint: 'Must match the name the bank or wallet has on file.',
    payoutsBankName: 'Bank name',
    payoutsBankNamePlaceholder: 'e.g. Meezan Bank',
    payoutsIbanHint: '24 characters, starting with PK. Spaces are fine.',
    payoutsMobileNumber: '{method} mobile number',
    payoutsPassword: 'Your Foodie password',
    payoutsPasswordPlaceholder: "Confirm it's you",
    payoutsPasswordHint: 'Required whenever payout details change.',
    payoutsSaveAccount: 'Save payout account',
    payoutsErrAccountTitle: 'Enter the name on the account',
    payoutsErrBankName: 'Enter your bank name',
    payoutsErrIban: 'IBAN must be PK followed by 22 letters or digits',
    payoutsErrMobile: 'Enter an 11-digit number like 03001234567',
    payoutsErrPassword: 'Enter your password to confirm this change',
  },
  {
    ur: {
      payoutsTitle: 'ادائیگیاں اور بلنگ',
      payoutsAccountSection: 'ادائیگی اکاؤنٹ',
      payoutsHowItWorks: 'ادائیگیاں کیسے ہوتی ہیں',
      payoutsInfoCommission: 'Foodie کا کمیشن ہر آرڈر کے کھانے کے ذیلی کل کا {rate} ہے۔',
      payoutsInfoFee: 'آن لائن آرڈرز پر {rate} ادائیگی پروسیسنگ فیس ہے۔',
      payoutsInfoCash: 'نقد آرڈرز کی رقم آپ کے پاس رہتی ہے، اس لیے ان کا کمیشن آپ کی آن لائن آمدنی سے کاٹا جاتا ہے۔',
      payoutsInfoDelivery: 'ڈیلیوری فیس اور رائیڈر ٹپس آپ کی ادائیگی میں شامل نہیں ہیں۔',
      payoutsHistory: 'ادائیگیوں کی تاریخ',
      payoutsHistoryEmpty:
        'ابھی کوئی ادائیگی نہیں۔ پہنچائے گئے آرڈرز وقتاً فوقتاً ادائیگی میں شامل کیے جاتے ہیں، اور ہر ادائیگی یہاں نظر آئے گی۔',
      payoutsOrderCount: '{count} آرڈرز',
      payoutsOrderCountOne: '1 آرڈر',
      payoutsShowOlder: 'پرانی ادائیگیاں دکھائیں',

      payoutsYouOwe: 'آپ پر Foodie کی رقم واجب ہے',
      payoutsFoodiePaysYou: 'Foodie آپ کو ادا کرے گا',
      payoutsUpcoming: 'آنے والی آمدنی',
      payoutsNoUnsettled: 'کوئی پہنچایا گیا آرڈر تصفیے کا منتظر نہیں',
      payoutsUnsettledFrom: '{count} پہنچائے گئے آرڈرز سے جو ابھی ادائیگی میں شامل نہیں',
      payoutsUnsettledFromOne: '1 پہنچائے گئے آرڈر سے جو ابھی ادائیگی میں شامل نہیں',
      payoutsSeeBreakdown: 'تفصیل دیکھیں',
      payoutsHideBreakdown: 'تفصیل چھپائیں',
      payoutsProcessingCount: 'زیرِ عمل ({count} ادائیگیاں)',
      payoutsProcessingCountOne: 'زیرِ عمل (1 ادائیگی)',
      payoutsLastPayout: 'آخری ادائیگی',

      payoutsAddAccountPrompt:
        'بینک اکاؤنٹ یا موبائل والیٹ شامل کریں تاکہ Foodie آپ کی آمدنی بھیج سکے۔ جب تک اکاؤنٹ شامل اور تصدیق شدہ نہ ہو، ادائیگیاں نہیں بھیجی جا سکتیں۔',
      payoutsAddAccount: 'ادائیگی اکاؤنٹ شامل کریں',
      payoutsEditAccount: 'ادائیگی اکاؤنٹ میں ترمیم',
      payoutsChangeAccount: 'ادائیگی اکاؤنٹ تبدیل کریں',
      payoutsVerifying: 'Foodie ان تفصیلات کی تصدیق کر رہا ہے۔ تصدیق کے بعد ادائیگیاں بھیجی جائیں گی۔',
      payoutsRejected: 'Foodie اس اکاؤنٹ کی تصدیق نہیں کر سکا۔ دوبارہ کوشش کے لیے تفصیلات اپ ڈیٹ کریں۔',
      payoutsRejectedReason: 'Foodie اس اکاؤنٹ کی تصدیق نہیں کر سکا: {reason} دوبارہ کوشش کے لیے تفصیلات اپ ڈیٹ کریں۔',

      payoutsDetailTitle: 'ادائیگی',
      payoutsReceived: 'وصول ہوئی',
      payoutsSent: 'بھیجی گئی',
      payoutsReceivedOn: '{date} کو وصول ہوئی',
      payoutsSentOn: '{date} کو بھیجی گئی',
      payoutsRef: 'حوالہ {reference}',
      payoutsFailedNote:
        'یہ منتقلی مکمل نہیں ہو سکی۔ چیک کریں کہ آپ کے ادائیگی اکاؤنٹ کی تفصیلات درست ہیں؛ Foodie اسے دوبارہ بھیجے گا۔',
      payoutsCollectNote: 'یہ رقم وصول کرنے کے لیے Foodie آپ سے رابطہ کرے گا۔',
      payoutsProcessingNote: 'Foodie یہ ادائیگی آپ کے اکاؤنٹ میں بھیجنے کے عمل میں ہے۔',
      payoutsOrdersInPayout: 'اس ادائیگی کے آرڈرز',
      payoutsCash: 'نقد',
      payoutsOnline: 'آن لائن',

      payoutsStatusProcessing: 'زیرِ عمل',
      payoutsStatusPending: 'زیرِ التوا',
      payoutsStatusPaid: 'ادا شدہ',
      payoutsStatusVerified: 'تصدیق شدہ',
      payoutsStatusFailed: 'ناکام',
      payoutsStatusRejected: 'مسترد',
      payoutsStatusNone: 'کوئی اکاؤنٹ نہیں',

      payoutsOnlineSales: 'آن لائن فروخت',
      payoutsCashSales: 'نقد فروخت (پہلے سے آپ کے پاس)',
      payoutsCommission: 'کمیشن ({gross} کا {rate})',
      payoutsPaymentFees: 'آن لائن ادائیگی فیس',

      payoutsFormIntro:
        'Foodie آپ کی آمدنی یہاں بھیجتا ہے۔ محفوظ کرنے کے بعد، Foodie اگلی ادائیگی سے پہلے تفصیلات کی تصدیق کرتا ہے۔',
      payoutsReceiveBy: 'ادائیگی وصول کرنے کا طریقہ',
      payoutsAccountTitle: 'اکاؤنٹ کا نام',
      payoutsAccountTitlePlaceholderBank: 'مثلاً Beef House Pvt Ltd',
      payoutsAccountTitlePlaceholderWallet: 'والیٹ پر رجسٹرڈ نام',
      payoutsAccountTitleHint: 'نام بینک یا والیٹ کے ریکارڈ سے مطابقت رکھتا ہو۔',
      payoutsBankName: 'بینک کا نام',
      payoutsBankNamePlaceholder: 'مثلاً Meezan Bank',
      payoutsIbanHint: '24 حروف، PK سے شروع۔ خالی جگہیں چل جائیں گی۔',
      payoutsMobileNumber: '{method} موبائل نمبر',
      payoutsPassword: 'آپ کا Foodie پاس ورڈ',
      payoutsPasswordPlaceholder: 'تصدیق کریں کہ یہ آپ ہیں',
      payoutsPasswordHint: 'ادائیگی کی تفصیلات بدلتے وقت ضروری ہے۔',
      payoutsSaveAccount: 'ادائیگی اکاؤنٹ محفوظ کریں',
      payoutsErrAccountTitle: 'اکاؤنٹ پر درج نام لکھیں',
      payoutsErrBankName: 'اپنے بینک کا نام لکھیں',
      payoutsErrIban: 'IBAN میں PK کے بعد 22 حروف یا ہندسے ہونے چاہئیں',
      payoutsErrMobile: '11 ہندسوں کا نمبر لکھیں، جیسے 03001234567',
      payoutsErrPassword: 'اس تبدیلی کی تصدیق کے لیے اپنا پاس ورڈ لکھیں',
    },
    es: {
      payoutsTitle: 'Pagos y facturación',
      payoutsAccountSection: 'Cuenta de pagos',
      payoutsHowItWorks: 'Cómo funcionan los pagos',
      payoutsInfoCommission: 'La comisión de Foodie es el {rate} del subtotal de comida de cada pedido.',
      payoutsInfoFee: 'Los pedidos en línea tienen una tarifa de procesamiento de pago del {rate}.',
      payoutsInfoCash:
        'En los pedidos en efectivo te quedas con el dinero, así que su comisión se descuenta de tus ganancias en línea.',
      payoutsInfoDelivery: 'Las tarifas de envío y las propinas del repartidor no forman parte de tu pago.',
      payoutsHistory: 'Historial de pagos',
      payoutsHistoryEmpty:
        'Aún no hay pagos. Los pedidos entregados se liquidan periódicamente en un pago, y cada uno aparecerá aquí.',
      payoutsOrderCount: '{count} pedidos',
      payoutsOrderCountOne: '1 pedido',
      payoutsShowOlder: 'Ver pagos anteriores',

      payoutsYouOwe: 'Le debes a Foodie',
      payoutsFoodiePaysYou: 'Foodie te paga',
      payoutsUpcoming: 'Próximas ganancias',
      payoutsNoUnsettled: 'No hay pedidos entregados pendientes de liquidar',
      payoutsUnsettledFrom: 'De {count} pedidos entregados aún sin pago',
      payoutsUnsettledFromOne: 'De 1 pedido entregado aún sin pago',
      payoutsSeeBreakdown: 'Ver desglose',
      payoutsHideBreakdown: 'Ocultar desglose',
      payoutsProcessingCount: 'En proceso ({count} pagos)',
      payoutsProcessingCountOne: 'En proceso (1 pago)',
      payoutsLastPayout: 'Último pago',

      payoutsAddAccountPrompt:
        'Añade una cuenta bancaria o billetera móvil para que Foodie pueda enviarte tus ganancias. No se pueden enviar pagos hasta que se añada y verifique una.',
      payoutsAddAccount: 'Añadir cuenta de pagos',
      payoutsEditAccount: 'Editar cuenta de pagos',
      payoutsChangeAccount: 'Cambiar cuenta de pagos',
      payoutsVerifying: 'Foodie está verificando estos datos. Los pagos se envían una vez verificados.',
      payoutsRejected: 'Foodie no pudo verificar esta cuenta. Actualiza los datos para intentarlo de nuevo.',
      payoutsRejectedReason:
        'Foodie no pudo verificar esta cuenta: {reason} Actualiza los datos para intentarlo de nuevo.',

      payoutsDetailTitle: 'Pago',
      payoutsReceived: 'Recibido',
      payoutsSent: 'Enviado',
      payoutsReceivedOn: 'Recibido el {date}',
      payoutsSentOn: 'Enviado el {date}',
      payoutsRef: 'Ref. {reference}',
      payoutsFailedNote:
        'Esta transferencia no se completó. Comprueba que los datos de tu cuenta de pagos sean correctos; Foodie la enviará de nuevo.',
      payoutsCollectNote: 'Foodie se pondrá en contacto contigo para cobrar este importe.',
      payoutsProcessingNote: 'Foodie está procesando este pago a tu cuenta.',
      payoutsOrdersInPayout: 'Pedidos de este pago',
      payoutsCash: 'Efectivo',
      payoutsOnline: 'En línea',

      payoutsStatusProcessing: 'En proceso',
      payoutsStatusPending: 'Pendiente',
      payoutsStatusPaid: 'Pagado',
      payoutsStatusVerified: 'Verificada',
      payoutsStatusFailed: 'Fallido',
      payoutsStatusRejected: 'Rechazada',
      payoutsStatusNone: 'Sin cuenta',

      payoutsOnlineSales: 'Ventas en línea',
      payoutsCashSales: 'Ventas en efectivo (ya en tu poder)',
      payoutsCommission: 'Comisión ({rate} de {gross})',
      payoutsPaymentFees: 'Tarifas de pago en línea',

      payoutsFormIntro:
        'Foodie envía tus ganancias aquí. Después de guardar, Foodie verifica los datos antes del próximo pago.',
      payoutsReceiveBy: 'Recibir pagos por',
      payoutsAccountTitle: 'Titular de la cuenta',
      payoutsAccountTitlePlaceholderBank: 'p. ej. Beef House Pvt Ltd',
      payoutsAccountTitlePlaceholderWallet: 'Nombre registrado en la billetera',
      payoutsAccountTitleHint: 'Debe coincidir con el nombre que tiene registrado el banco o la billetera.',
      payoutsBankName: 'Nombre del banco',
      payoutsBankNamePlaceholder: 'p. ej. Meezan Bank',
      payoutsIbanHint: '24 caracteres, empezando por PK. Puedes usar espacios.',
      payoutsMobileNumber: 'Número móvil de {method}',
      payoutsPassword: 'Tu contraseña de Foodie',
      payoutsPasswordPlaceholder: 'Confirma que eres tú',
      payoutsPasswordHint: 'Obligatoria cada vez que cambien los datos de pago.',
      payoutsSaveAccount: 'Guardar cuenta de pagos',
      payoutsErrAccountTitle: 'Introduce el nombre del titular',
      payoutsErrBankName: 'Introduce el nombre de tu banco',
      payoutsErrIban: 'El IBAN debe ser PK seguido de 22 letras o dígitos',
      payoutsErrMobile: 'Introduce un número de 11 dígitos como 03001234567',
      payoutsErrPassword: 'Introduce tu contraseña para confirmar este cambio',
    },
    fr: {
      payoutsTitle: 'Paiements et facturation',
      payoutsAccountSection: 'Compte de versement',
      payoutsHowItWorks: 'Fonctionnement des versements',
      payoutsInfoCommission: 'La commission de Foodie est de {rate} du sous-total repas de chaque commande.',
      payoutsInfoFee: 'Les commandes en ligne ont des frais de traitement de paiement de {rate}.',
      payoutsInfoCash:
        "Pour les commandes en espèces, vous gardez l'argent : leur commission est donc prélevée sur vos gains en ligne.",
      payoutsInfoDelivery: 'Les frais de livraison et les pourboires des livreurs ne font pas partie de votre versement.',
      payoutsHistory: 'Historique des versements',
      payoutsHistoryEmpty:
        'Aucun versement pour le moment. Les commandes livrées sont réglées périodiquement dans un versement, qui apparaîtra ici.',
      payoutsOrderCount: '{count} commandes',
      payoutsOrderCountOne: '1 commande',
      payoutsShowOlder: 'Voir les versements plus anciens',

      payoutsYouOwe: 'Vous devez à Foodie',
      payoutsFoodiePaysYou: 'Foodie vous verse',
      payoutsUpcoming: 'Gains à venir',
      payoutsNoUnsettled: 'Aucune commande livrée en attente de règlement',
      payoutsUnsettledFrom: 'De {count} commandes livrées pas encore versées',
      payoutsUnsettledFromOne: "D'1 commande livrée pas encore versée",
      payoutsSeeBreakdown: 'Voir le détail',
      payoutsHideBreakdown: 'Masquer le détail',
      payoutsProcessingCount: 'En cours ({count} versements)',
      payoutsProcessingCountOne: 'En cours (1 versement)',
      payoutsLastPayout: 'Dernier versement',

      payoutsAddAccountPrompt:
        "Ajoutez un compte bancaire ou un portefeuille mobile pour que Foodie puisse vous verser vos gains. Aucun versement n'est possible tant qu'un compte n'est pas ajouté et vérifié.",
      payoutsAddAccount: 'Ajouter un compte de versement',
      payoutsEditAccount: 'Modifier le compte de versement',
      payoutsChangeAccount: 'Changer de compte de versement',
      payoutsVerifying: 'Foodie vérifie ces informations. Les versements sont envoyés une fois vérifiées.',
      payoutsRejected: "Foodie n'a pas pu vérifier ce compte. Mettez à jour les informations pour réessayer.",
      payoutsRejectedReason:
        "Foodie n'a pas pu vérifier ce compte : {reason} Mettez à jour les informations pour réessayer.",

      payoutsDetailTitle: 'Versement',
      payoutsReceived: 'Reçu',
      payoutsSent: 'Envoyé',
      payoutsReceivedOn: 'Reçu le {date}',
      payoutsSentOn: 'Envoyé le {date}',
      payoutsRef: 'Réf. {reference}',
      payoutsFailedNote:
        "Ce virement n'a pas abouti. Vérifiez les informations de votre compte de versement ; Foodie le renverra.",
      payoutsCollectNote: 'Foodie vous contactera pour percevoir ce montant.',
      payoutsProcessingNote: 'Foodie traite ce versement vers votre compte.',
      payoutsOrdersInPayout: 'Commandes de ce versement',
      payoutsCash: 'Espèces',
      payoutsOnline: 'En ligne',

      payoutsStatusProcessing: 'En cours',
      payoutsStatusPending: 'En attente',
      payoutsStatusPaid: 'Payé',
      payoutsStatusVerified: 'Vérifié',
      payoutsStatusFailed: 'Échoué',
      payoutsStatusRejected: 'Refusé',
      payoutsStatusNone: 'Aucun compte',

      payoutsOnlineSales: 'Ventes en ligne',
      payoutsCashSales: 'Ventes en espèces (déjà chez vous)',
      payoutsCommission: 'Commission ({rate} de {gross})',
      payoutsPaymentFees: 'Frais de paiement en ligne',

      payoutsFormIntro:
        'Foodie vous verse vos gains ici. Après enregistrement, Foodie vérifie les informations avant le prochain versement.',
      payoutsReceiveBy: 'Recevoir les versements par',
      payoutsAccountTitle: 'Titulaire du compte',
      payoutsAccountTitlePlaceholderBank: 'ex. Beef House Pvt Ltd',
      payoutsAccountTitlePlaceholderWallet: 'Nom enregistré sur le portefeuille',
      payoutsAccountTitleHint: 'Doit correspondre au nom enregistré par la banque ou le portefeuille.',
      payoutsBankName: 'Nom de la banque',
      payoutsBankNamePlaceholder: 'ex. Meezan Bank',
      payoutsIbanHint: 'Commence par PK, 24 caractères. Les espaces sont acceptés.',
      payoutsMobileNumber: 'Numéro mobile {method}',
      payoutsPassword: 'Votre mot de passe Foodie',
      payoutsPasswordPlaceholder: "Confirmez qu'il s'agit bien de vous",
      payoutsPasswordHint: 'Requis à chaque modification des informations de versement.',
      payoutsSaveAccount: 'Enregistrer le compte',
      payoutsErrAccountTitle: 'Saisissez le nom du titulaire',
      payoutsErrBankName: 'Saisissez le nom de votre banque',
      payoutsErrIban: "L'IBAN doit commencer par PK suivi de 22 lettres ou chiffres",
      payoutsErrMobile: 'Saisissez un numéro à 11 chiffres, ex. 03001234567',
      payoutsErrPassword: 'Saisissez votre mot de passe pour confirmer ce changement',
    },
  },
);
