import { defineStrings } from './define';

/** Profile tab: general/account/settings tabs and their modals. */
export default defineStrings(
  {
    profileLoadFailed: 'Failed to load profile',
    profileSignOutTitle: 'Sign Out',
    profileSignOutConfirm: 'Are you sure you want to sign out?',
    profileSignOutCaps: 'SIGN OUT',
    profileVerified: 'Verified',

    profileTabGeneral: 'General',
    profileTabAccount: 'Account',
    profileTabSettings: 'Settings',

    profileOperatingHoursCaps: 'OPERATING HOURS',
    profileHoursMonThu: 'Mon - Thu',
    profileHoursFriSat: 'Fri - Sat',
    profileClosed: 'Closed',
    profileUpdateHours: 'Update Hours',
    profileHoursUpdateFailed: 'Failed to update hours',
    profileOperatingHoursTitle: 'Operating Hours',
    profileTimeTo: 'to',
    profileDayMonday: 'Monday',
    profileDayTuesday: 'Tuesday',
    profileDayWednesday: 'Wednesday',
    profileDayThursday: 'Thursday',
    profileDayFriday: 'Friday',
    profileDaySaturday: 'Saturday',
    profileDaySunday: 'Sunday',

    profileAccountPerformance: 'Account Performance',
    profileRatingCaps: 'RATING',
    profileTotalOrdersCaps: 'TOTAL ORDERS',
    profilePremierPartner: 'Premier Partner',
    profileTopLocal: 'Top 5% Locally',

    profileDeliverySettingsCaps: 'DELIVERY SETTINGS',
    profileDeliverySettingsTitle: 'Delivery Settings',
    profileEditDeliverySettings: 'Edit delivery settings',
    profileEdit: 'Edit',
    profileDeliveryRadius: 'Delivery Radius',
    profileMinimumOrder: 'Minimum Order',
    profileDeliveryFee: 'Delivery Fee',
    profileEstimatedTime: 'Estimated Time',
    profileDeliveryRadiusHint: 'How far from your restaurant you deliver',
    profileMinimumOrderHint: 'Smallest subtotal a customer can check out with',
    profileDeliveryFeeHint: 'Set to 0 to offer free delivery',
    profileEstimatedTimeHint: 'Average time from order to doorstep',
    profileUnitKm: 'km',
    profileUnitMin: 'min',
    profileFree: 'Free',
    profileFieldRequired: '{field} is required',
    profileInvalidNumber: 'Enter a valid number',
    profileOutOfRange: 'Must be between {min} and {max}',
    profileDeliveryUpdateFailed: 'Failed to update delivery settings',
    profileDeliveryFootnote: 'Changes apply to new orders only. Orders already placed keep their original fee.',

    profilePaymentMethodsCaps: 'PAYMENT METHODS',
    profilePaymentCash: 'Cash',
    profilePaymentCard: 'Card',
    profilePaymentWallet: 'Wallet',
    profilePaymentOnline: 'Online',
    profilePaymentRequired: 'At least one payment method is required',

    profileSettingsTitle: 'Restaurant Settings',
    profileDarkMode: 'Dark mode',
    profileDarkModeHint: 'Restaurant app uses the same appearance as the rest of Foodie',
    profileStoreInfo: 'Store Information',
    profileStoreInfoHint: 'Update description and restaurant cover',
    profileNotificationPrefs: 'Notification Preferences',
    profileNotificationPrefsHint: 'Order alerts, marketing, and reviews',
    profilePayoutsBilling: 'Payouts & Billing',
    profilePayoutsBillingHint: 'Earnings, payout account & history',

    profileNotificationsTitle: 'Notifications',
    profileNotifLoadFailed: 'Failed to load notification preferences',
    profileNotifUpdateFailed: 'Failed to update notification preferences',
    profileNotifAllOff: "All channels are off, so you won't receive any alerts — including new orders.",
    profileNotifAutoSave: 'Changes are saved automatically.',
    profileNotifOrderAlerts: 'Order alerts',
    profileNotifOrderAlertsDesc: 'Stay on top of the kitchen pipeline',
    profileNotifBusiness: 'Business',
    profileNotifBusinessDesc: 'Feedback and money matters',
    profileNotifChannels: 'Delivery channels',
    profileNotifChannelsDesc: 'Where we reach you',
    profileNotifNewOrders: 'New orders',
    profileNotifNewOrdersHint: 'Alert me the moment a customer places an order',
    profileNotifCancellations: 'Cancellations',
    profileNotifCancellationsHint: 'When a customer or rider cancels an order',
    profileNotifReviews: 'Reviews & ratings',
    profileNotifReviewsHint: 'When customers leave a new review',
    profileNotifPayouts: 'Payouts',
    profileNotifPayoutsHint: 'Payout confirmations and billing notices',
    profileNotifWeeklySummary: 'Weekly summary',
    profileNotifWeeklySummaryHint: 'Orders, revenue and ratings recap every Monday',
    profileNotifMarketing: 'Tips & promotions',
    profileNotifMarketingHint: 'Growth tips and Foodie promotional campaigns',
    profileNotifPush: 'Push notifications',
    profileNotifPushHint: 'On this device',
    profileNotifEmail: 'Email',
    profileNotifEmailHint: 'Coming soon — sent to your restaurant account email',
    profileNotifSms: 'SMS',
    profileNotifSmsHint: 'Coming soon — text messages to your restaurant phone',

    profileRestaurantImages: 'Restaurant Images',
    profileUploading: 'Uploading…',
    profileAddImage: 'Add Image',
    profileDescription: 'Description',
    profileDescriptionHint: 'Tell customers about your restaurant',
    profileDescriptionPlaceholder: 'e.g., Award-winning Italian restaurant with authentic recipes...',
    profileDescriptionTooShort: 'Description must be at least 10 characters',
    profileDescriptionTooLong: 'Description cannot exceed 500 characters',
    profileImageRequired: 'Please add at least one image',
    profileImageUploadFailed: 'Failed to upload image',
    profileSuccess: 'Success',
    profileStoreInfoUpdated: 'Store information updated successfully',
    profileStoreInfoUpdateFailed: 'Failed to update store information',
  },
  {
    ur: {
      profileLoadFailed: 'پروفائل لوڈ نہیں ہو سکی',
      profileSignOutTitle: 'سائن آؤٹ',
      profileSignOutConfirm: 'کیا آپ واقعی سائن آؤٹ کرنا چاہتے ہیں؟',
      profileSignOutCaps: 'سائن آؤٹ',
      profileVerified: 'تصدیق شدہ',

      profileTabGeneral: 'عمومی',
      profileTabAccount: 'اکاؤنٹ',
      profileTabSettings: 'ترتیبات',

      profileOperatingHoursCaps: 'اوقاتِ کار',
      profileHoursMonThu: 'پیر - جمعرات',
      profileHoursFriSat: 'جمعہ - ہفتہ',
      profileClosed: 'بند',
      profileUpdateHours: 'اوقات تبدیل کریں',
      profileHoursUpdateFailed: 'اوقات اپ ڈیٹ نہیں ہو سکے',
      profileOperatingHoursTitle: 'اوقاتِ کار',
      profileTimeTo: 'تا',
      profileDayMonday: 'پیر',
      profileDayTuesday: 'منگل',
      profileDayWednesday: 'بدھ',
      profileDayThursday: 'جمعرات',
      profileDayFriday: 'جمعہ',
      profileDaySaturday: 'ہفتہ',
      profileDaySunday: 'اتوار',

      profileAccountPerformance: 'اکاؤنٹ کی کارکردگی',
      profileRatingCaps: 'ریٹنگ',
      profileTotalOrdersCaps: 'کل آرڈرز',
      profilePremierPartner: 'پریمیئر پارٹنر',
      profileTopLocal: 'علاقے کے ٹاپ 5%',

      profileDeliverySettingsCaps: 'ڈیلیوری کی ترتیبات',
      profileDeliverySettingsTitle: 'ڈیلیوری کی ترتیبات',
      profileEditDeliverySettings: 'ڈیلیوری کی ترتیبات میں ترمیم کریں',
      profileEdit: 'ترمیم',
      profileDeliveryRadius: 'ڈیلیوری کا دائرہ',
      profileMinimumOrder: 'کم از کم آرڈر',
      profileDeliveryFee: 'ڈیلیوری فیس',
      profileEstimatedTime: 'متوقع وقت',
      profileDeliveryRadiusHint: 'آپ ریسٹورنٹ سے کتنی دور تک ڈیلیور کرتے ہیں',
      profileMinimumOrderHint: 'کم از کم رقم جس پر گاہک چیک آؤٹ کر سکے',
      profileDeliveryFeeHint: 'مفت ڈیلیوری کے لیے 0 رکھیں',
      profileEstimatedTimeHint: 'آرڈر سے دروازے تک اوسط وقت',
      profileUnitKm: 'کلومیٹر',
      profileUnitMin: 'منٹ',
      profileFree: 'مفت',
      profileFieldRequired: '{field} ضروری ہے',
      profileInvalidNumber: 'درست نمبر درج کریں',
      profileOutOfRange: '{min} اور {max} کے درمیان ہونا چاہیے',
      profileDeliveryUpdateFailed: 'ڈیلیوری کی ترتیبات اپ ڈیٹ نہیں ہو سکیں',
      profileDeliveryFootnote: 'تبدیلیاں صرف نئے آرڈرز پر لاگو ہوں گی۔ پہلے سے دیے گئے آرڈرز کی فیس وہی رہے گی۔',

      profilePaymentMethodsCaps: 'ادائیگی کے طریقے',
      profilePaymentCash: 'نقد',
      profilePaymentCard: 'کارڈ',
      profilePaymentWallet: 'والٹ',
      profilePaymentOnline: 'آن لائن',
      profilePaymentRequired: 'کم از کم ایک ادائیگی کا طریقہ ضروری ہے',

      profileSettingsTitle: 'ریسٹورنٹ کی ترتیبات',
      profileDarkMode: 'ڈارک موڈ',
      profileDarkModeHint: 'ریسٹورنٹ ایپ باقی Foodie جیسی ہی شکل استعمال کرتی ہے',
      profileStoreInfo: 'اسٹور کی معلومات',
      profileStoreInfoHint: 'تفصیل اور ریسٹورنٹ کی تصاویر اپ ڈیٹ کریں',
      profileNotificationPrefs: 'نوٹیفکیشن کی ترجیحات',
      profileNotificationPrefsHint: 'آرڈر الرٹس، مارکیٹنگ اور ریویوز',
      profilePayoutsBilling: 'ادائیگیاں اور بلنگ',
      profilePayoutsBillingHint: 'آمدنی، ادائیگی اکاؤنٹ اور تاریخچہ',

      profileNotificationsTitle: 'نوٹیفکیشنز',
      profileNotifLoadFailed: 'نوٹیفکیشن کی ترجیحات لوڈ نہیں ہو سکیں',
      profileNotifUpdateFailed: 'نوٹیفکیشن کی ترجیحات اپ ڈیٹ نہیں ہو سکیں',
      profileNotifAllOff: 'تمام چینلز بند ہیں، اس لیے آپ کو کوئی الرٹ نہیں ملے گا — نئے آرڈرز کا بھی نہیں۔',
      profileNotifAutoSave: 'تبدیلیاں خود بخود محفوظ ہو جاتی ہیں۔',
      profileNotifOrderAlerts: 'آرڈر الرٹس',
      profileNotifOrderAlertsDesc: 'کچن کے ہر آرڈر سے باخبر رہیں',
      profileNotifBusiness: 'کاروبار',
      profileNotifBusinessDesc: 'آراء اور مالی معاملات',
      profileNotifChannels: 'رابطے کے ذرائع',
      profileNotifChannelsDesc: 'ہم آپ تک کہاں پہنچیں',
      profileNotifNewOrders: 'نئے آرڈرز',
      profileNotifNewOrdersHint: 'گاہک کے آرڈر دیتے ہی مجھے اطلاع دیں',
      profileNotifCancellations: 'منسوخیاں',
      profileNotifCancellationsHint: 'جب گاہک یا رائیڈر آرڈر منسوخ کرے',
      profileNotifReviews: 'ریویوز اور ریٹنگز',
      profileNotifReviewsHint: 'جب گاہک نیا ریویو دیں',
      profileNotifPayouts: 'ادائیگیاں',
      profileNotifPayoutsHint: 'ادائیگی کی تصدیق اور بلنگ کے نوٹس',
      profileNotifWeeklySummary: 'ہفتہ وار خلاصہ',
      profileNotifWeeklySummaryHint: 'ہر پیر کو آرڈرز، آمدنی اور ریٹنگز کا خلاصہ',
      profileNotifMarketing: 'مشورے اور پروموشنز',
      profileNotifMarketingHint: 'ترقی کے مشورے اور Foodie کی پروموشنل مہمات',
      profileNotifPush: 'پش نوٹیفکیشنز',
      profileNotifPushHint: 'اس ڈیوائس پر',
      profileNotifEmail: 'ای میل',
      profileNotifEmailHint: 'جلد آ رہا ہے — آپ کے ریسٹورنٹ اکاؤنٹ کی ای میل پر',
      profileNotifSms: 'ایس ایم ایس',
      profileNotifSmsHint: 'جلد آ رہا ہے — آپ کے ریسٹورنٹ کے فون پر پیغامات',

      profileRestaurantImages: 'ریسٹورنٹ کی تصاویر',
      profileUploading: 'اپ لوڈ ہو رہا ہے…',
      profileAddImage: 'تصویر شامل کریں',
      profileDescription: 'تفصیل',
      profileDescriptionHint: 'گاہکوں کو اپنے ریسٹورنٹ کے بارے میں بتائیں',
      profileDescriptionPlaceholder: 'مثلاً، اصل ترکیبوں والا ایوارڈ یافتہ اطالوی ریسٹورنٹ...',
      profileDescriptionTooShort: 'تفصیل کم از کم 10 حروف کی ہونی چاہیے',
      profileDescriptionTooLong: 'تفصیل 500 حروف سے زیادہ نہیں ہو سکتی',
      profileImageRequired: 'براہِ کرم کم از کم ایک تصویر شامل کریں',
      profileImageUploadFailed: 'تصویر اپ لوڈ نہیں ہو سکی',
      profileSuccess: 'کامیابی',
      profileStoreInfoUpdated: 'اسٹور کی معلومات کامیابی سے اپ ڈیٹ ہو گئیں',
      profileStoreInfoUpdateFailed: 'اسٹور کی معلومات اپ ڈیٹ نہیں ہو سکیں',
    },
    es: {
      profileLoadFailed: 'No se pudo cargar el perfil',
      profileSignOutTitle: 'Cerrar sesión',
      profileSignOutConfirm: '¿Seguro que quieres cerrar sesión?',
      profileSignOutCaps: 'CERRAR SESIÓN',
      profileVerified: 'Verificado',

      profileTabGeneral: 'General',
      profileTabAccount: 'Cuenta',
      profileTabSettings: 'Ajustes',

      profileOperatingHoursCaps: 'HORARIO',
      profileHoursMonThu: 'Lun - Jue',
      profileHoursFriSat: 'Vie - Sáb',
      profileClosed: 'Cerrado',
      profileUpdateHours: 'Cambiar horario',
      profileHoursUpdateFailed: 'No se pudo actualizar el horario',
      profileOperatingHoursTitle: 'Horario',
      profileTimeTo: 'a',
      profileDayMonday: 'Lunes',
      profileDayTuesday: 'Martes',
      profileDayWednesday: 'Miércoles',
      profileDayThursday: 'Jueves',
      profileDayFriday: 'Viernes',
      profileDaySaturday: 'Sábado',
      profileDaySunday: 'Domingo',

      profileAccountPerformance: 'Rendimiento de la cuenta',
      profileRatingCaps: 'VALORACIÓN',
      profileTotalOrdersCaps: 'PEDIDOS TOTALES',
      profilePremierPartner: 'Socio Premier',
      profileTopLocal: 'Top 5% local',

      profileDeliverySettingsCaps: 'AJUSTES DE ENTREGA',
      profileDeliverySettingsTitle: 'Ajustes de entrega',
      profileEditDeliverySettings: 'Editar ajustes de entrega',
      profileEdit: 'Editar',
      profileDeliveryRadius: 'Radio de entrega',
      profileMinimumOrder: 'Pedido mínimo',
      profileDeliveryFee: 'Tarifa de envío',
      profileEstimatedTime: 'Tiempo estimado',
      profileDeliveryRadiusHint: 'Hasta qué distancia de tu restaurante entregas',
      profileMinimumOrderHint: 'Subtotal mínimo para que un cliente pueda pagar',
      profileDeliveryFeeHint: 'Pon 0 para ofrecer envío gratis',
      profileEstimatedTimeHint: 'Tiempo medio desde el pedido hasta la puerta',
      profileUnitKm: 'km',
      profileUnitMin: 'min',
      profileFree: 'Gratis',
      profileFieldRequired: '{field} es obligatorio',
      profileInvalidNumber: 'Introduce un número válido',
      profileOutOfRange: 'Debe estar entre {min} y {max}',
      profileDeliveryUpdateFailed: 'No se pudieron actualizar los ajustes de entrega',
      profileDeliveryFootnote: 'Los cambios solo se aplican a pedidos nuevos. Los pedidos ya realizados mantienen su tarifa original.',

      profilePaymentMethodsCaps: 'MÉTODOS DE PAGO',
      profilePaymentCash: 'Efectivo',
      profilePaymentCard: 'Tarjeta',
      profilePaymentWallet: 'Monedero',
      profilePaymentOnline: 'En línea',
      profilePaymentRequired: 'Se requiere al menos un método de pago',

      profileSettingsTitle: 'Ajustes del restaurante',
      profileDarkMode: 'Modo oscuro',
      profileDarkModeHint: 'La app del restaurante usa la misma apariencia que el resto de Foodie',
      profileStoreInfo: 'Información de la tienda',
      profileStoreInfoHint: 'Actualiza la descripción y la portada del restaurante',
      profileNotificationPrefs: 'Preferencias de notificaciones',
      profileNotificationPrefsHint: 'Alertas de pedidos, marketing y reseñas',
      profilePayoutsBilling: 'Pagos y facturación',
      profilePayoutsBillingHint: 'Ganancias, cuenta de cobro e historial',

      profileNotificationsTitle: 'Notificaciones',
      profileNotifLoadFailed: 'No se pudieron cargar las preferencias de notificaciones',
      profileNotifUpdateFailed: 'No se pudieron actualizar las preferencias de notificaciones',
      profileNotifAllOff: 'Todos los canales están desactivados, así que no recibirás ninguna alerta, ni siquiera de pedidos nuevos.',
      profileNotifAutoSave: 'Los cambios se guardan automáticamente.',
      profileNotifOrderAlerts: 'Alertas de pedidos',
      profileNotifOrderAlertsDesc: 'Mantente al día con la cocina',
      profileNotifBusiness: 'Negocio',
      profileNotifBusinessDesc: 'Opiniones y asuntos de dinero',
      profileNotifChannels: 'Canales de aviso',
      profileNotifChannelsDesc: 'Dónde te avisamos',
      profileNotifNewOrders: 'Pedidos nuevos',
      profileNotifNewOrdersHint: 'Avisarme en cuanto un cliente haga un pedido',
      profileNotifCancellations: 'Cancelaciones',
      profileNotifCancellationsHint: 'Cuando un cliente o repartidor cancela un pedido',
      profileNotifReviews: 'Reseñas y valoraciones',
      profileNotifReviewsHint: 'Cuando los clientes dejan una reseña nueva',
      profileNotifPayouts: 'Pagos',
      profileNotifPayoutsHint: 'Confirmaciones de pago y avisos de facturación',
      profileNotifWeeklySummary: 'Resumen semanal',
      profileNotifWeeklySummaryHint: 'Resumen de pedidos, ingresos y valoraciones cada lunes',
      profileNotifMarketing: 'Consejos y promociones',
      profileNotifMarketingHint: 'Consejos de crecimiento y campañas promocionales de Foodie',
      profileNotifPush: 'Notificaciones push',
      profileNotifPushHint: 'En este dispositivo',
      profileNotifEmail: 'Correo electrónico',
      profileNotifEmailHint: 'Próximamente: al correo de tu cuenta de restaurante',
      profileNotifSms: 'SMS',
      profileNotifSmsHint: 'Próximamente: mensajes al teléfono de tu restaurante',

      profileRestaurantImages: 'Imágenes del restaurante',
      profileUploading: 'Subiendo…',
      profileAddImage: 'Añadir imagen',
      profileDescription: 'Descripción',
      profileDescriptionHint: 'Cuenta a los clientes sobre tu restaurante',
      profileDescriptionPlaceholder: 'p. ej., restaurante italiano premiado con recetas auténticas...',
      profileDescriptionTooShort: 'La descripción debe tener al menos 10 caracteres',
      profileDescriptionTooLong: 'La descripción no puede superar los 500 caracteres',
      profileImageRequired: 'Añade al menos una imagen',
      profileImageUploadFailed: 'No se pudo subir la imagen',
      profileSuccess: 'Listo',
      profileStoreInfoUpdated: 'Información de la tienda actualizada',
      profileStoreInfoUpdateFailed: 'No se pudo actualizar la información de la tienda',
    },
    fr: {
      profileLoadFailed: 'Impossible de charger le profil',
      profileSignOutTitle: 'Se déconnecter',
      profileSignOutConfirm: 'Voulez-vous vraiment vous déconnecter ?',
      profileSignOutCaps: 'SE DÉCONNECTER',
      profileVerified: 'Vérifié',

      profileTabGeneral: 'Général',
      profileTabAccount: 'Compte',
      profileTabSettings: 'Réglages',

      profileOperatingHoursCaps: "HORAIRES D'OUVERTURE",
      profileHoursMonThu: 'Lun - Jeu',
      profileHoursFriSat: 'Ven - Sam',
      profileClosed: 'Fermé',
      profileUpdateHours: 'Modifier les horaires',
      profileHoursUpdateFailed: 'Impossible de mettre à jour les horaires',
      profileOperatingHoursTitle: "Horaires d'ouverture",
      profileTimeTo: 'à',
      profileDayMonday: 'Lundi',
      profileDayTuesday: 'Mardi',
      profileDayWednesday: 'Mercredi',
      profileDayThursday: 'Jeudi',
      profileDayFriday: 'Vendredi',
      profileDaySaturday: 'Samedi',
      profileDaySunday: 'Dimanche',

      profileAccountPerformance: 'Performance du compte',
      profileRatingCaps: 'NOTE',
      profileTotalOrdersCaps: 'TOTAL DES COMMANDES',
      profilePremierPartner: 'Partenaire Premier',
      profileTopLocal: 'Top 5 % local',

      profileDeliverySettingsCaps: 'PARAMÈTRES DE LIVRAISON',
      profileDeliverySettingsTitle: 'Paramètres de livraison',
      profileEditDeliverySettings: 'Modifier les paramètres de livraison',
      profileEdit: 'Modifier',
      profileDeliveryRadius: 'Rayon de livraison',
      profileMinimumOrder: 'Commande minimum',
      profileDeliveryFee: 'Frais de livraison',
      profileEstimatedTime: 'Temps estimé',
      profileDeliveryRadiusHint: "Jusqu'où vous livrez depuis votre restaurant",
      profileMinimumOrderHint: 'Sous-total minimum pour pouvoir commander',
      profileDeliveryFeeHint: 'Mettez 0 pour offrir la livraison',
      profileEstimatedTimeHint: "Durée moyenne de la commande jusqu'à la porte",
      profileUnitKm: 'km',
      profileUnitMin: 'min',
      profileFree: 'Gratuit',
      profileFieldRequired: '{field} est obligatoire',
      profileInvalidNumber: 'Saisissez un nombre valide',
      profileOutOfRange: 'Doit être compris entre {min} et {max}',
      profileDeliveryUpdateFailed: 'Impossible de mettre à jour les paramètres de livraison',
      profileDeliveryFootnote: 'Les changements ne s’appliquent qu’aux nouvelles commandes. Les commandes déjà passées gardent leurs frais d’origine.',

      profilePaymentMethodsCaps: 'MOYENS DE PAIEMENT',
      profilePaymentCash: 'Espèces',
      profilePaymentCard: 'Carte',
      profilePaymentWallet: 'Portefeuille',
      profilePaymentOnline: 'En ligne',
      profilePaymentRequired: 'Au moins un moyen de paiement est requis',

      profileSettingsTitle: 'Réglages du restaurant',
      profileDarkMode: 'Mode sombre',
      profileDarkModeHint: "L'app restaurant utilise la même apparence que le reste de Foodie",
      profileStoreInfo: 'Infos du restaurant',
      profileStoreInfoHint: 'Modifier la description et la couverture',
      profileNotificationPrefs: 'Préférences de notifications',
      profileNotificationPrefsHint: 'Alertes de commande, marketing et avis',
      profilePayoutsBilling: 'Paiements et facturation',
      profilePayoutsBillingHint: 'Revenus, compte de versement et historique',

      profileNotificationsTitle: 'Notifications',
      profileNotifLoadFailed: 'Impossible de charger les préférences de notifications',
      profileNotifUpdateFailed: 'Impossible de mettre à jour les préférences de notifications',
      profileNotifAllOff: 'Tous les canaux sont désactivés : vous ne recevrez aucune alerte, pas même pour les nouvelles commandes.',
      profileNotifAutoSave: 'Les modifications sont enregistrées automatiquement.',
      profileNotifOrderAlerts: 'Alertes de commande',
      profileNotifOrderAlertsDesc: 'Gardez un œil sur la cuisine',
      profileNotifBusiness: 'Activité',
      profileNotifBusinessDesc: 'Avis et questions financières',
      profileNotifChannels: 'Canaux de réception',
      profileNotifChannelsDesc: 'Où nous vous joignons',
      profileNotifNewOrders: 'Nouvelles commandes',
      profileNotifNewOrdersHint: "M'avertir dès qu'un client passe commande",
      profileNotifCancellations: 'Annulations',
      profileNotifCancellationsHint: 'Quand un client ou un livreur annule une commande',
      profileNotifReviews: 'Avis et notes',
      profileNotifReviewsHint: 'Quand un client laisse un nouvel avis',
      profileNotifPayouts: 'Versements',
      profileNotifPayoutsHint: 'Confirmations de versement et avis de facturation',
      profileNotifWeeklySummary: 'Résumé hebdomadaire',
      profileNotifWeeklySummaryHint: 'Récap des commandes, revenus et notes chaque lundi',
      profileNotifMarketing: 'Conseils et promotions',
      profileNotifMarketingHint: 'Conseils de croissance et campagnes promotionnelles Foodie',
      profileNotifPush: 'Notifications push',
      profileNotifPushHint: 'Sur cet appareil',
      profileNotifEmail: 'E-mail',
      profileNotifEmailHint: "Bientôt disponible — envoyé à l'e-mail de votre compte restaurant",
      profileNotifSms: 'SMS',
      profileNotifSmsHint: 'Bientôt disponible — SMS au téléphone de votre restaurant',

      profileRestaurantImages: 'Photos du restaurant',
      profileUploading: 'Envoi…',
      profileAddImage: 'Ajouter une photo',
      profileDescription: 'Description',
      profileDescriptionHint: 'Présentez votre restaurant aux clients',
      profileDescriptionPlaceholder: 'ex. : restaurant italien primé aux recettes authentiques...',
      profileDescriptionTooShort: 'La description doit contenir au moins 10 caractères',
      profileDescriptionTooLong: 'La description ne peut pas dépasser 500 caractères',
      profileImageRequired: 'Ajoutez au moins une photo',
      profileImageUploadFailed: "Impossible d'envoyer la photo",
      profileSuccess: 'Succès',
      profileStoreInfoUpdated: 'Infos du restaurant mises à jour',
      profileStoreInfoUpdateFailed: 'Impossible de mettre à jour les infos du restaurant',
    },
  },
);
