/**
 * UI strings for the customer app. English is the source of truth: every other
 * language must define every key (enforced by the `Strings` type), so a missing
 * translation is a type error rather than blank text.
 *
 * Use `{name}` placeholders for values, e.g. t('itemsCount', { count: 3 }).
 * Restaurant names, dish names and descriptions come from restaurants and are
 * never translated.
 */

export type CustomerLanguage = 'en' | 'ur' | 'es' | 'fr';

export const CUSTOMER_LANGUAGES: { code: CustomerLanguage; label: string; nativeLabel: string }[] = [
  { code: 'en', label: 'English', nativeLabel: 'English' },
  { code: 'ur', label: 'Urdu', nativeLabel: 'اردو' },
  { code: 'es', label: 'Spanish', nativeLabel: 'Español' },
  { code: 'fr', label: 'French', nativeLabel: 'Français' },
];

const en = {
  // Common
  cancel: 'Cancel',
  save: 'Save',
  close: 'Close',
  back: 'Back',
  retry: 'Try again',
  error: 'Error',

  // Profile › Settings
  preferences: 'PREFERENCES',
  darkMode: 'Dark mode',
  darkModeHint: 'Easier on the eyes in low light',
  notificationSettings: 'Notification Settings',
  notificationSettingsHintOn: 'Order updates on',
  notificationSettingsHintOff: 'Push notifications off',
  language: 'Language',
  legalAbout: 'LEGAL & ABOUT',
  privacyPolicy: 'Privacy Policy',
  termsOfService: 'Terms of Service',
  appVersion: 'App Version',
  logOut: 'Log Out',
  loggedInAs: 'Logged in as {email}',

  // Language sheet
  chooseLanguage: 'Choose language',
  languageSheetHint:
    'Menus, buttons and order updates will use this language. Restaurant and dish names stay as the restaurant wrote them.',
  languageSaveFailed: "Couldn't save your language on the server. It's still used on this device.",

  // Notification settings sheet
  notificationsTitle: 'Notifications',
  pushNotifications: 'Push notifications',
  pushNotificationsHint: 'Allow Foodie to send notifications to this device',
  orderUpdates: 'Order updates',
  orderUpdatesHint: 'Confirmed, preparing, on the way and delivered',
  promotions: 'Offers & promotions',
  promotionsHint: 'Deals and discounts from restaurants you like',
  notificationsBlocked:
    'Notifications are turned off for Foodie in your phone settings, so nothing can be shown.',
  openSettings: 'Open settings',
  notificationsSaveFailed: "Couldn't save that change. Check your connection and try again.",
  notificationsSaved: 'Changes are saved automatically.',

  // Tabs
  tabExplore: 'Explore',
  tabSearch: 'Search',
  tabCart: 'Cart',
  tabProfile: 'Profile',

  // Home
  deliverTo: 'Deliver to',
  goodMorning: 'Good Morning',
  goodAfternoon: 'Good Afternoon',
  goodEvening: 'Good Evening',
  homeSearchPlaceholder: 'Search for sushi, pasta, or burgers…',
  categories: 'Categories',
  viewAll: 'View All',
  categoryAll: 'All',
  popularNearYou: 'Popular Near You',
  allRestaurants: 'All Restaurants',
  placesOne: '{count} place',
  placesOther: '{count} places',
  noRestaurantsFound: 'No restaurants found',
  yourOrder: 'Your order',
  orderHeadlinePending: 'Waiting for the restaurant',
  orderHeadlineConfirmed: 'Order confirmed',
  orderHeadlinePreparing: 'Preparing your order',
  orderHeadlineReady: 'Your food is ready',
  orderHeadlinePickedUp: 'Rider picked up your order',
  orderHeadlineOutForDelivery: 'On the way to you',
  tapForDetails: 'Tap to see details',
  enjoyYourMeal: 'Enjoy your meal!',
  arrivingAround: 'Arriving ~{time}',
  riderDelivering: '{name} is delivering your order',
  openOrderA11y: '{headline}, {restaurant}. Open order',
  dismissOrderUpdate: 'Dismiss order update',
  trackOrder: 'Track order',
  moreOrdersOne: '+{count} more order',
  moreOrdersOther: '+{count} more orders',
  moreOrdersA11yOne: '{count} more order. Open order history',
  moreOrdersA11yOther: '{count} more orders. Open order history',

  // Search
  searchPlaceholder: 'Search for restaurants and groceries',
  searching: 'Searching...',
  noResults: 'No results found',
  noResultsHint: 'Try a different search term',
  popularCuisines: 'Popular cuisines',
  recentSearches: 'Recent searches',
  popularSearches: 'Popular searches in restaurants',
  searchResults: 'Results ({count})',
  freeDelivery: 'Free Delivery',
  minutesShort: '{count} min',

  // Profile
  profileTabPersonal: 'Personal',
  profileTabBusiness: 'Business',
  profileTabSettings: 'Settings',
  logOutConfirm: 'Are you sure you want to log out?',

  // Profile › Personal
  guestUser: 'Guest User',
  premiumMember: 'PREMIUM MEMBER',
  personalInformation: 'Personal Information',
  orderHistory: 'Order History',
  paymentMethods: 'Payment Methods',
  loyaltyPoints: 'Loyalty Points',
  pointsCount: '{count} pts',
  loyaltyHint: 'Earn points on every order',

  // Profile › Business
  yourPath: 'Your Path',
  yourPathHint: 'Choose how you want to partner with the culinary world.',
  partnerTier: 'PARTNER TIER',
  restaurantOwner: 'Restaurant Owner',
  restaurantOwnerHint: 'Reach thousands of hungry customers and scale your kitchen operations with our professional logistics network.',
  registerStore: 'Register Store',
  alreadyRegistered: 'Already registered? Sign in →',
  flexibleWork: 'FLEXIBLE WORK',
  deliveryDriver: 'Delivery Driver',
  deliveryDriverHint: 'Be your own boss. Earn competitive rates while delivering the best culinary experiences in your city.',
  becomeRider: 'Become a Rider',
  alreadyRider: 'Already a rider? Sign in →',
  weeklyPayouts: 'Weekly Payouts',
  weeklyPayoutsHint: 'Direct deposit every Monday morning.',
  support247: '24/7 Support',
  support247Hint: 'Priority help for business partners.',

  // Cart
  removeItem: 'Remove Item',
  removeItemConfirm: 'Remove {name} from cart?',
  remove: 'Remove',
  clearCart: 'Clear Cart',
  clearCartConfirm: 'Remove all items?',
  clear: 'Clear',
  yourCart: 'Your Cart',
  cartFrom: 'from {restaurant}',
  itemsOne: '{count} item',
  itemsOther: '{count} items',
  removeNamed: 'Remove {name}',
  priceEach: '{price} each',
  decreaseQty: 'Decrease {name} quantity',
  increaseQty: 'Increase {name} quantity',
  quantityA11y: 'Quantity {count}',
  cartEmpty: 'Your Cart is Empty',
  cartEmptyHint: 'Add items from a restaurant to get started',
  browseRestaurants: 'Browse Restaurants',
  yourLastOrder: 'Your last order',
  deliveredOn: 'Delivered {date}',
  orderAgain: 'Order again',
  popularRightNow: 'Popular right now',
  popularRightNowHint: 'What others have ordered most this month',
  popularItemA11y: '{name} from {restaurant}, {price}',
  ordersCountOne: '{count} order',
  ordersCountOther: '{count} orders',
  someItemsUnavailable: 'Some items are unavailable',
  notAdded: 'Not added: {items}',
  reorderFailed: 'Could not reorder',
  orderSummary: 'ORDER SUMMARY',
  subtotal: 'Subtotal',
  deliveryFee: 'Delivery fee',
  taxesFees: 'Taxes & fees',
  total: 'Total',
  checkoutWithTotal: 'Checkout, total {total}',
  ok: 'OK',
  viewOrder: 'View Order',
  orderNotPlacedCartRestored: 'Your order was not placed and your cart has been restored.',
  orderNotUndone: 'Order #{number} could not be undone.',
  paymentSuccessful: 'Payment Successful',
  paymentSuccessfulMessage: 'Order #{number} confirmed and paid via Safepay.',
  paymentPending: 'Payment Pending',
  paymentPendingMessage: "Order #{number} was placed. We'll confirm payment shortly.",
  paymentCancelled: 'Payment Cancelled',
  paymentCancelledMessage: 'You cancelled the payment.',
  paymentFailed: 'Payment Failed',
  paymentFailedReason: 'Safepay reported: {reason}.',
  paymentFailedMessage: 'Your payment did not go through.',
  orderPlaced: 'Order Placed!',
  orderPlacedCashMessage: 'Your order #{number} has been placed. Pay the rider on delivery.',
  placeOrderFailed: 'Failed to place order',
  checkoutFailed: 'Checkout Failed',

  // Saved addresses
  savedAddresses: 'Saved Addresses',
  addNewAddress: 'Add new address',
  editAddress: 'Edit address',
  addressLabel: 'Label',
  labelHome: 'Home',
  labelWork: 'Work',
  labelOther: 'Other',
  customLabelPlaceholder: 'Name this place (e.g. Gym)',
  deliveryInstructions: 'Delivery instructions (optional)',
  setAsDefault: 'Set as default address',
  defaultBadge: 'Default',
  makeDefault: 'Make default',
  editAction: 'Edit',
  deleteAction: 'Delete',
  deleteAddressTitle: 'Delete address',
  deleteAddressConfirm: 'Remove "{label}" from your saved addresses?',
  noSavedAddresses: 'No saved addresses yet',
  noSavedAddressesHint: 'Save your home or work address and checkout takes one tap.',
  addDeliveryAddress: 'Add delivery address',
  chooseDeliveryAddress: 'Choose delivery address',
  manageAddresses: 'Manage addresses',
  saveToMyAddresses: 'Save to my addresses',
  useSavedAddress: 'Use a saved address',
  addressSaveFailed: "Couldn't save address",

  // Checkout
  checkout: 'Checkout',
  closeCheckout: 'Close checkout',
  validation: 'Validation',
  fillDeliveryAddress: 'Please fill in delivery address',
  deliveryAddress: 'Delivery Address',
  streetAddress: 'Street address',
  city: 'City',
  zipCode: 'Zip Code',
  paymentMethod: 'Payment Method',
  payWithSafepay: 'Pay with Safepay',
  payWithSafepayHint: 'Card / Wallet — secure online checkout',
  cashOnDelivery: 'Cash on Delivery',
  cashOnDeliveryHint: 'Pay the rider in cash on arrival',
  deliveryNotes: 'Delivery Notes',
  deliveryNotesPlaceholder: 'Add instructions for the rider (e.g., Gate code, floor number...)',
  placeOrder: 'Place Order',
  placingOrder: 'Placing Order...',
  safepaySecureNote: 'Card and wallet payments are processed securely by Safepay',

  // Order status
  orderStatusTitle: 'Order Status',
  loadingOrder: 'Loading your order...',
  loadOrderFailed: 'Could not load order status',
  estArrival: 'Est. arrival {time}',
  phasePlaced: 'Order Placed',
  phaseOnTheWay: 'On the Way',
  inProgress: 'In progress…',
  orderCancelledTitle: 'Order Cancelled',
  orderCancelledHint: 'This order was cancelled. If this was unexpected, please contact support.',
  thanksForReview: 'Thanks for your review',
  rateYourOrder: 'Rate your order',
  continueShopping: 'Continue Shopping',
  viewAllOrders: 'View All Orders',
  statusPending: 'Pending',
  statusConfirmed: 'Confirmed',
  statusPreparing: 'Preparing',
  statusReady: 'Ready',
  statusPickedUp: 'Picked up',
  statusOutForDelivery: 'Out for delivery',
  statusDelivered: 'Delivered',
  statusCancelled: 'Cancelled',

  // Order history
  loadOrdersFailed: 'Could not load orders',
  noOrdersYet: 'No orders yet',
  noOrdersHint: 'Your past orders will appear here.',
  moreItemsOne: '+{count} more',
  moreItemsOther: '+{count} more',
  restaurantFallback: 'Restaurant',
  reviewed: 'Reviewed',
  rate: 'Rate',

  // Restaurant menu
  loadRestaurantFailed: 'Failed to load restaurant details',
  addToCartFailed: 'Failed to add to cart',
  restaurantNotFound: 'Restaurant not found',
  premiumDelivery: 'PREMIUM DELIVERY',
  free: 'Free',
  closed: 'Closed',
  premiumBadge: 'PREMIUM',
  minOrder: 'Min {amount}',
  ratingA11yOne: 'Rated {rating} out of 5 from {count} review',
  ratingA11yOther: 'Rated {rating} out of 5 from {count} reviews',
  tagVeg: 'VEG',
  tagVegan: 'VEGAN',
  tagGlutenFree: 'GF',
  addToCart: 'Add to Cart',
  unavailable: 'Unavailable',
  noMenuItems: 'No menu items available',
  viewCart: 'VIEW CART',
  viewCartA11yOne: 'View cart, {count} item',
  viewCartA11yOther: 'View cart, {count} items',

  // Review
  reviewNotSaved: 'Review not saved',
  pleaseRefresh: 'Please refresh.',
  reviewSubmitFailed: 'Could not submit review',
  pleaseTryAgain: 'Please try again.',
  reviewCommentPlaceholder: 'What did you think? (optional)',
  commentFor: 'Comment for {name}',
  addComment: 'Add a comment',
  yourRiderNamed: 'Your rider, {name}',
  yourRider: 'Your rider',
  reviewDeliveryLabel: 'DELIVERY',
  reviewsFinal: "Reviews can't be edited after submitting.",
  rateMoreOne: 'Rate {count} more to submit',
  rateMoreOther: 'Rate {count} more to submit',
  submitReview: 'Submit review',
};

type Strings = Record<keyof typeof en, string>;
export type CustomerStringKey = keyof typeof en;

const ur: Strings = {
  cancel: 'منسوخ',
  save: 'محفوظ کریں',
  close: 'بند کریں',
  back: 'واپس',
  retry: 'دوبارہ کوشش کریں',
  error: 'خرابی',

  preferences: 'ترجیحات',
  darkMode: 'ڈارک موڈ',
  darkModeHint: 'کم روشنی میں آنکھوں کے لیے آرام دہ',
  notificationSettings: 'نوٹیفکیشن کی ترتیبات',
  notificationSettingsHintOn: 'آرڈر اپڈیٹس آن ہیں',
  notificationSettingsHintOff: 'پش نوٹیفکیشنز بند ہیں',
  language: 'زبان',
  legalAbout: 'قانونی اور تعارف',
  privacyPolicy: 'رازداری کی پالیسی',
  termsOfService: 'شرائط و ضوابط',
  appVersion: 'ایپ ورژن',
  logOut: 'لاگ آؤٹ',
  loggedInAs: '{email} کے طور پر لاگ ان',

  chooseLanguage: 'زبان منتخب کریں',
  languageSheetHint:
    'مینو، بٹن اور آرڈر اپڈیٹس اسی زبان میں ہوں گے۔ ریسٹورنٹ اور کھانوں کے نام ویسے ہی رہیں گے جیسے ریسٹورنٹ نے لکھے ہیں۔',
  languageSaveFailed: 'آپ کی زبان سرور پر محفوظ نہیں ہو سکی۔ اس ڈیوائس پر یہی زبان استعمال ہو رہی ہے۔',

  notificationsTitle: 'نوٹیفکیشنز',
  pushNotifications: 'پش نوٹیفکیشنز',
  pushNotificationsHint: 'Foodie کو اس ڈیوائس پر نوٹیفکیشن بھیجنے دیں',
  orderUpdates: 'آرڈر اپڈیٹس',
  orderUpdatesHint: 'کنفرم، تیاری، راستے میں اور ڈیلیور',
  promotions: 'آفرز اور پروموشنز',
  promotionsHint: 'آپ کے پسندیدہ ریسٹورنٹس کی ڈیلز اور رعایتیں',
  notificationsBlocked: 'فون کی ترتیبات میں Foodie کے نوٹیفکیشنز بند ہیں، اس لیے کچھ نہیں دکھایا جا سکتا۔',
  openSettings: 'ترتیبات کھولیں',
  notificationsSaveFailed: 'تبدیلی محفوظ نہیں ہو سکی۔ کنکشن چیک کر کے دوبارہ کوشش کریں۔',
  notificationsSaved: 'تبدیلیاں خود بخود محفوظ ہو جاتی ہیں۔',

  // Tabs
  tabExplore: 'ایکسپلور',
  tabSearch: 'تلاش',
  tabCart: 'کارٹ',
  tabProfile: 'پروفائل',

  // Home
  deliverTo: 'ڈیلیوری کا پتہ',
  goodMorning: 'صبح بخیر',
  goodAfternoon: 'دوپہر بخیر',
  goodEvening: 'شام بخیر',
  homeSearchPlaceholder: 'سوشی، پاستا یا برگر تلاش کریں…',
  categories: 'کیٹیگریز',
  viewAll: 'سب دیکھیں',
  categoryAll: 'سب',
  popularNearYou: 'آپ کے قریب مقبول',
  allRestaurants: 'تمام ریسٹورنٹس',
  placesOne: '{count} ریسٹورنٹ',
  placesOther: '{count} ریسٹورنٹس',
  noRestaurantsFound: 'کوئی ریسٹورنٹ نہیں ملا',
  yourOrder: 'آپ کا آرڈر',
  orderHeadlinePending: 'ریسٹورنٹ کا انتظار ہے',
  orderHeadlineConfirmed: 'آرڈر کنفرم ہو گیا',
  orderHeadlinePreparing: 'آپ کا آرڈر تیار ہو رہا ہے',
  orderHeadlineReady: 'آپ کا کھانا تیار ہے',
  orderHeadlinePickedUp: 'رائیڈر نے آپ کا آرڈر اٹھا لیا',
  orderHeadlineOutForDelivery: 'آپ کی طرف روانہ',
  tapForDetails: 'تفصیلات کے لیے ٹیپ کریں',
  enjoyYourMeal: 'کھانے کا لطف اٹھائیں!',
  arrivingAround: 'تقریباً {time} تک',
  riderDelivering: '{name} آپ کا آرڈر پہنچا رہے ہیں',
  openOrderA11y: '{headline}، {restaurant}۔ آرڈر کھولیں',
  dismissOrderUpdate: 'آرڈر اپڈیٹ ہٹائیں',
  trackOrder: 'آرڈر ٹریک کریں',
  moreOrdersOne: '+{count} مزید آرڈر',
  moreOrdersOther: '+{count} مزید آرڈرز',
  moreOrdersA11yOne: '{count} مزید آرڈر۔ آرڈر ہسٹری کھولیں',
  moreOrdersA11yOther: '{count} مزید آرڈرز۔ آرڈر ہسٹری کھولیں',

  // Search
  searchPlaceholder: 'ریسٹورنٹس اور گروسری تلاش کریں',
  searching: 'تلاش جاری ہے…',
  noResults: 'کوئی نتیجہ نہیں ملا',
  noResultsHint: 'کوئی اور لفظ تلاش کر کے دیکھیں',
  popularCuisines: 'مقبول کھانے',
  recentSearches: 'حالیہ تلاش',
  popularSearches: 'ریسٹورنٹس میں مقبول تلاش',
  searchResults: 'نتائج ({count})',
  freeDelivery: 'مفت ڈیلیوری',
  minutesShort: '{count} منٹ',

  // Profile
  profileTabPersonal: 'ذاتی',
  profileTabBusiness: 'کاروبار',
  profileTabSettings: 'ترتیبات',
  logOutConfirm: 'کیا آپ واقعی لاگ آؤٹ کرنا چاہتے ہیں؟',

  // Profile › Personal
  guestUser: 'مہمان صارف',
  premiumMember: 'پریمیم ممبر',
  personalInformation: 'ذاتی معلومات',
  orderHistory: 'آرڈر ہسٹری',
  paymentMethods: 'ادائیگی کے طریقے',
  loyaltyPoints: 'لائلٹی پوائنٹس',
  pointsCount: '{count} پوائنٹس',
  loyaltyHint: 'ہر آرڈر پر پوائنٹس کمائیں',

  // Profile › Business
  yourPath: 'آپ کا راستہ',
  yourPathHint: 'منتخب کریں کہ آپ کھانوں کی دنیا کے ساتھ کیسے شراکت کرنا چاہتے ہیں۔',
  partnerTier: 'پارٹنر',
  restaurantOwner: 'ریسٹورنٹ مالک',
  restaurantOwnerHint: 'ہزاروں بھوکے گاہکوں تک پہنچیں اور ہمارے پیشہ ورانہ لاجسٹکس نیٹ ورک کے ساتھ اپنا کاروبار بڑھائیں۔',
  registerStore: 'اسٹور رجسٹر کریں',
  alreadyRegistered: 'پہلے سے رجسٹرڈ ہیں؟ سائن ان کریں ←',
  flexibleWork: 'لچکدار کام',
  deliveryDriver: 'ڈیلیوری رائیڈر',
  deliveryDriverHint: 'اپنے مالک خود بنیں۔ اپنے شہر میں بہترین کھانے پہنچائیں اور اچھی کمائی کریں۔',
  becomeRider: 'رائیڈر بنیں',
  alreadyRider: 'پہلے سے رائیڈر ہیں؟ سائن ان کریں ←',
  weeklyPayouts: 'ہفتہ وار ادائیگی',
  weeklyPayoutsHint: 'ہر پیر کی صبح براہِ راست اکاؤنٹ میں۔',
  support247: '24/7 سپورٹ',
  support247Hint: 'کاروباری شراکت داروں کے لیے ترجیحی مدد۔',

  // Cart
  removeItem: 'آئٹم ہٹائیں',
  removeItemConfirm: '{name} کو کارٹ سے ہٹائیں؟',
  remove: 'ہٹائیں',
  clearCart: 'کارٹ خالی کریں',
  clearCartConfirm: 'تمام آئٹمز ہٹائیں؟',
  clear: 'خالی کریں',
  yourCart: 'آپ کا کارٹ',
  cartFrom: '{restaurant} سے',
  itemsOne: '{count} آئٹم',
  itemsOther: '{count} آئٹمز',
  removeNamed: '{name} ہٹائیں',
  priceEach: '{price} فی عدد',
  decreaseQty: '{name} کی تعداد کم کریں',
  increaseQty: '{name} کی تعداد بڑھائیں',
  quantityA11y: 'تعداد {count}',
  cartEmpty: 'آپ کا کارٹ خالی ہے',
  cartEmptyHint: 'شروع کرنے کے لیے کسی ریسٹورنٹ سے آئٹمز شامل کریں',
  browseRestaurants: 'ریسٹورنٹس دیکھیں',
  yourLastOrder: 'آپ کا پچھلا آرڈر',
  deliveredOn: '{date} کو ڈیلیور ہوا',
  orderAgain: 'دوبارہ آرڈر کریں',
  popularRightNow: 'ابھی مقبول',
  popularRightNowHint: 'اس مہینے سب سے زیادہ آرڈر کیے گئے کھانے',
  popularItemA11y: '{restaurant} کا {name}، {price}',
  ordersCountOne: '{count} آرڈر',
  ordersCountOther: '{count} آرڈرز',
  someItemsUnavailable: 'کچھ آئٹمز دستیاب نہیں',
  notAdded: 'شامل نہیں کیے گئے: {items}',
  reorderFailed: 'دوبارہ آرڈر نہیں ہو سکا',
  orderSummary: 'آرڈر کا خلاصہ',
  subtotal: 'ذیلی کل',
  deliveryFee: 'ڈیلیوری فیس',
  taxesFees: 'ٹیکس اور فیس',
  total: 'کل رقم',
  checkoutWithTotal: 'چیک آؤٹ، کل {total}',
  ok: 'ٹھیک ہے',
  viewOrder: 'آرڈر دیکھیں',
  orderNotPlacedCartRestored: 'آپ کا آرڈر نہیں دیا گیا اور آپ کا کارٹ بحال کر دیا گیا ہے۔',
  orderNotUndone: 'آرڈر #{number} واپس نہیں لیا جا سکا۔',
  paymentSuccessful: 'ادائیگی کامیاب',
  paymentSuccessfulMessage: 'آرڈر #{number} کنفرم ہو گیا اور Safepay کے ذریعے ادائیگی ہو گئی۔',
  paymentPending: 'ادائیگی زیرِ التواء',
  paymentPendingMessage: 'آرڈر #{number} دے دیا گیا ہے۔ ہم جلد ادائیگی کی تصدیق کریں گے۔',
  paymentCancelled: 'ادائیگی منسوخ',
  paymentCancelledMessage: 'آپ نے ادائیگی منسوخ کر دی۔',
  paymentFailed: 'ادائیگی ناکام',
  paymentFailedReason: 'Safepay کے مطابق: {reason}۔',
  paymentFailedMessage: 'آپ کی ادائیگی مکمل نہیں ہو سکی۔',
  orderPlaced: 'آرڈر دے دیا گیا!',
  orderPlacedCashMessage: 'آپ کا آرڈر #{number} دے دیا گیا ہے۔ ڈیلیوری پر رائیڈر کو ادائیگی کریں۔',
  placeOrderFailed: 'آرڈر نہیں دیا جا سکا',
  checkoutFailed: 'چیک آؤٹ ناکام',

  // Saved addresses
  savedAddresses: 'محفوظ پتے',
  addNewAddress: 'نیا پتہ شامل کریں',
  editAddress: 'پتہ تبدیل کریں',
  addressLabel: 'نام',
  labelHome: 'گھر',
  labelWork: 'دفتر',
  labelOther: 'دیگر',
  customLabelPlaceholder: 'اس جگہ کا نام (مثلاً جم)',
  deliveryInstructions: 'ڈیلیوری ہدایات (اختیاری)',
  setAsDefault: 'بطور ڈیفالٹ پتہ مقرر کریں',
  defaultBadge: 'ڈیفالٹ',
  makeDefault: 'ڈیفالٹ بنائیں',
  editAction: 'ترمیم',
  deleteAction: 'حذف کریں',
  deleteAddressTitle: 'پتہ حذف کریں',
  deleteAddressConfirm: 'کیا "{label}" کو محفوظ پتوں سے ہٹا دیں؟',
  noSavedAddresses: 'ابھی کوئی پتہ محفوظ نہیں',
  noSavedAddressesHint: 'گھر یا دفتر کا پتہ محفوظ کریں، چیک آؤٹ ایک ٹیپ میں ہو جائے گا۔',
  addDeliveryAddress: 'ڈیلیوری کا پتہ شامل کریں',
  chooseDeliveryAddress: 'ڈیلیوری کا پتہ منتخب کریں',
  manageAddresses: 'پتوں کا انتظام',
  saveToMyAddresses: 'میرے پتوں میں محفوظ کریں',
  useSavedAddress: 'محفوظ پتہ استعمال کریں',
  addressSaveFailed: 'پتہ محفوظ نہیں ہو سکا',

  // Checkout
  checkout: 'چیک آؤٹ',
  closeCheckout: 'چیک آؤٹ بند کریں',
  validation: 'معلومات نامکمل',
  fillDeliveryAddress: 'براہِ کرم ڈیلیوری کا پتہ درج کریں',
  deliveryAddress: 'ڈیلیوری کا پتہ',
  streetAddress: 'گلی / مکان کا پتہ',
  city: 'شہر',
  zipCode: 'زپ کوڈ',
  paymentMethod: 'ادائیگی کا طریقہ',
  payWithSafepay: 'Safepay سے ادائیگی',
  payWithSafepayHint: 'کارڈ / والیٹ — محفوظ آن لائن ادائیگی',
  cashOnDelivery: 'کیش آن ڈیلیوری',
  cashOnDeliveryHint: 'پہنچنے پر رائیڈر کو نقد ادائیگی کریں',
  deliveryNotes: 'ڈیلیوری ہدایات',
  deliveryNotesPlaceholder: 'رائیڈر کے لیے ہدایات لکھیں (مثلاً گیٹ کوڈ، منزل…)',
  placeOrder: 'آرڈر دیں',
  placingOrder: 'آرڈر دیا جا رہا ہے…',
  safepaySecureNote: 'کارڈ اور والیٹ کی ادائیگیاں Safepay کے ذریعے محفوظ طریقے سے ہوتی ہیں',

  // Order status
  orderStatusTitle: 'آرڈر کی صورتحال',
  loadingOrder: 'آپ کا آرڈر لوڈ ہو رہا ہے…',
  loadOrderFailed: 'آرڈر کی صورتحال لوڈ نہیں ہو سکی',
  estArrival: 'متوقع آمد {time}',
  phasePlaced: 'آرڈر دے دیا گیا',
  phaseOnTheWay: 'راستے میں',
  inProgress: 'جاری ہے…',
  orderCancelledTitle: 'آرڈر منسوخ',
  orderCancelledHint: 'یہ آرڈر منسوخ کر دیا گیا۔ اگر یہ غیر متوقع تھا تو براہِ کرم سپورٹ سے رابطہ کریں۔',
  thanksForReview: 'ریویو دینے کا شکریہ',
  rateYourOrder: 'اپنے آرڈر کو ریٹ کریں',
  continueShopping: 'خریداری جاری رکھیں',
  viewAllOrders: 'تمام آرڈرز دیکھیں',
  statusPending: 'زیرِ التواء',
  statusConfirmed: 'کنفرم',
  statusPreparing: 'تیار ہو رہا ہے',
  statusReady: 'تیار',
  statusPickedUp: 'رائیڈر کے پاس',
  statusOutForDelivery: 'ڈیلیوری کے لیے روانہ',
  statusDelivered: 'ڈیلیور ہو گیا',
  statusCancelled: 'منسوخ',

  // Order history
  loadOrdersFailed: 'آرڈرز لوڈ نہیں ہو سکے',
  noOrdersYet: 'ابھی تک کوئی آرڈر نہیں',
  noOrdersHint: 'آپ کے پچھلے آرڈرز یہاں نظر آئیں گے۔',
  moreItemsOne: '+{count} مزید',
  moreItemsOther: '+{count} مزید',
  restaurantFallback: 'ریسٹورنٹ',
  reviewed: 'ریویو ہو گیا',
  rate: 'ریٹ کریں',

  // Restaurant menu
  loadRestaurantFailed: 'ریسٹورنٹ کی تفصیلات لوڈ نہیں ہو سکیں',
  addToCartFailed: 'کارٹ میں شامل نہیں ہو سکا',
  restaurantNotFound: 'ریسٹورنٹ نہیں ملا',
  premiumDelivery: 'پریمیم ڈیلیوری',
  free: 'مفت',
  closed: 'بند',
  premiumBadge: 'پریمیم',
  minOrder: 'کم از کم {amount}',
  ratingA11yOne: '{count} ریویو کی بنیاد پر 5 میں سے {rating}',
  ratingA11yOther: '{count} ریویوز کی بنیاد پر 5 میں سے {rating}',
  tagVeg: 'سبزی',
  tagVegan: 'ویگن',
  tagGlutenFree: 'گلوٹن فری',
  addToCart: 'کارٹ میں ڈالیں',
  unavailable: 'دستیاب نہیں',
  noMenuItems: 'مینو میں کوئی آئٹم دستیاب نہیں',
  viewCart: 'کارٹ دیکھیں',
  viewCartA11yOne: 'کارٹ دیکھیں، {count} آئٹم',
  viewCartA11yOther: 'کارٹ دیکھیں، {count} آئٹمز',

  // Review
  reviewNotSaved: 'ریویو محفوظ نہیں ہوا',
  pleaseRefresh: 'براہِ کرم ریفریش کریں۔',
  reviewSubmitFailed: 'ریویو جمع نہیں ہو سکا',
  pleaseTryAgain: 'براہِ کرم دوبارہ کوشش کریں۔',
  reviewCommentPlaceholder: 'آپ کی کیا رائے ہے؟ (اختیاری)',
  commentFor: '{name} پر تبصرہ',
  addComment: 'تبصرہ شامل کریں',
  yourRiderNamed: 'آپ کے رائیڈر، {name}',
  yourRider: 'آپ کے رائیڈر',
  reviewDeliveryLabel: 'ڈیلیوری',
  reviewsFinal: 'جمع کرانے کے بعد ریویو میں تبدیلی نہیں ہو سکتی۔',
  rateMoreOne: 'جمع کرانے کے لیے {count} مزید ریٹ کریں',
  rateMoreOther: 'جمع کرانے کے لیے {count} مزید ریٹ کریں',
  submitReview: 'ریویو جمع کریں',
};

const es: Strings = {
  cancel: 'Cancelar',
  save: 'Guardar',
  close: 'Cerrar',
  back: 'Atrás',
  retry: 'Reintentar',
  error: 'Error',

  preferences: 'PREFERENCIAS',
  darkMode: 'Modo oscuro',
  darkModeHint: 'Más cómodo con poca luz',
  notificationSettings: 'Notificaciones',
  notificationSettingsHintOn: 'Avisos de pedidos activados',
  notificationSettingsHintOff: 'Notificaciones desactivadas',
  language: 'Idioma',
  legalAbout: 'LEGAL E INFORMACIÓN',
  privacyPolicy: 'Política de privacidad',
  termsOfService: 'Términos del servicio',
  appVersion: 'Versión de la app',
  logOut: 'Cerrar sesión',
  loggedInAs: 'Sesión iniciada como {email}',

  chooseLanguage: 'Elige un idioma',
  languageSheetHint:
    'Los menús, botones y avisos de pedidos usarán este idioma. Los nombres de restaurantes y platos se muestran como los escribió el restaurante.',
  languageSaveFailed: 'No se pudo guardar tu idioma en el servidor. Se sigue usando en este dispositivo.',

  notificationsTitle: 'Notificaciones',
  pushNotifications: 'Notificaciones push',
  pushNotificationsHint: 'Permite que Foodie envíe notificaciones a este dispositivo',
  orderUpdates: 'Estado del pedido',
  orderUpdatesHint: 'Confirmado, en preparación, en camino y entregado',
  promotions: 'Ofertas y promociones',
  promotionsHint: 'Descuentos de los restaurantes que te gustan',
  notificationsBlocked:
    'Las notificaciones de Foodie están desactivadas en los ajustes del teléfono, así que no se puede mostrar nada.',
  openSettings: 'Abrir ajustes',
  notificationsSaveFailed: 'No se pudo guardar el cambio. Revisa tu conexión e inténtalo de nuevo.',
  notificationsSaved: 'Los cambios se guardan automáticamente.',

  // Tabs
  tabExplore: 'Explorar',
  tabSearch: 'Buscar',
  tabCart: 'Carrito',
  tabProfile: 'Perfil',

  // Home
  deliverTo: 'Entregar en',
  goodMorning: 'Buenos días',
  goodAfternoon: 'Buenas tardes',
  goodEvening: 'Buenas noches',
  homeSearchPlaceholder: 'Busca sushi, pasta o hamburguesas…',
  categories: 'Categorías',
  viewAll: 'Ver todo',
  categoryAll: 'Todo',
  popularNearYou: 'Populares cerca de ti',
  allRestaurants: 'Todos los restaurantes',
  placesOne: '{count} lugar',
  placesOther: '{count} lugares',
  noRestaurantsFound: 'No se encontraron restaurantes',
  yourOrder: 'Tu pedido',
  orderHeadlinePending: 'Esperando al restaurante',
  orderHeadlineConfirmed: 'Pedido confirmado',
  orderHeadlinePreparing: 'Preparando tu pedido',
  orderHeadlineReady: 'Tu comida está lista',
  orderHeadlinePickedUp: 'El repartidor recogió tu pedido',
  orderHeadlineOutForDelivery: 'En camino hacia ti',
  tapForDetails: 'Toca para ver detalles',
  enjoyYourMeal: '¡Buen provecho!',
  arrivingAround: 'Llega ~{time}',
  riderDelivering: '{name} está entregando tu pedido',
  openOrderA11y: '{headline}, {restaurant}. Abrir pedido',
  dismissOrderUpdate: 'Descartar aviso del pedido',
  trackOrder: 'Seguir pedido',
  moreOrdersOne: '+{count} pedido más',
  moreOrdersOther: '+{count} pedidos más',
  moreOrdersA11yOne: '{count} pedido más. Abrir historial',
  moreOrdersA11yOther: '{count} pedidos más. Abrir historial',

  // Search
  searchPlaceholder: 'Busca restaurantes y supermercados',
  searching: 'Buscando…',
  noResults: 'No hay resultados',
  noResultsHint: 'Prueba con otra búsqueda',
  popularCuisines: 'Cocinas populares',
  recentSearches: 'Búsquedas recientes',
  popularSearches: 'Búsquedas populares en restaurantes',
  searchResults: 'Resultados ({count})',
  freeDelivery: 'Envío gratis',
  minutesShort: '{count} min',

  // Profile
  profileTabPersonal: 'Personal',
  profileTabBusiness: 'Negocios',
  profileTabSettings: 'Ajustes',
  logOutConfirm: '¿Seguro que quieres cerrar sesión?',

  // Profile › Personal
  guestUser: 'Invitado',
  premiumMember: 'MIEMBRO PREMIUM',
  personalInformation: 'Información personal',
  orderHistory: 'Historial de pedidos',
  paymentMethods: 'Métodos de pago',
  loyaltyPoints: 'Puntos de fidelidad',
  pointsCount: '{count} pts',
  loyaltyHint: 'Gana puntos con cada pedido',

  // Profile › Business
  yourPath: 'Tu camino',
  yourPathHint: 'Elige cómo quieres asociarte con el mundo gastronómico.',
  partnerTier: 'SOCIO',
  restaurantOwner: 'Dueño de restaurante',
  restaurantOwnerHint: 'Llega a miles de clientes con hambre y haz crecer tu cocina con nuestra red logística profesional.',
  registerStore: 'Registrar tienda',
  alreadyRegistered: '¿Ya estás registrado? Inicia sesión →',
  flexibleWork: 'HORARIO FLEXIBLE',
  deliveryDriver: 'Repartidor',
  deliveryDriverHint: 'Sé tu propio jefe. Gana tarifas competitivas llevando la mejor comida de tu ciudad.',
  becomeRider: 'Hazte repartidor',
  alreadyRider: '¿Ya eres repartidor? Inicia sesión →',
  weeklyPayouts: 'Pagos semanales',
  weeklyPayoutsHint: 'Depósito directo cada lunes por la mañana.',
  support247: 'Soporte 24/7',
  support247Hint: 'Ayuda prioritaria para socios.',

  // Cart
  removeItem: 'Quitar producto',
  removeItemConfirm: '¿Quitar {name} del carrito?',
  remove: 'Quitar',
  clearCart: 'Vaciar carrito',
  clearCartConfirm: '¿Quitar todos los productos?',
  clear: 'Vaciar',
  yourCart: 'Tu carrito',
  cartFrom: 'de {restaurant}',
  itemsOne: '{count} producto',
  itemsOther: '{count} productos',
  removeNamed: 'Quitar {name}',
  priceEach: '{price} c/u',
  decreaseQty: 'Reducir cantidad de {name}',
  increaseQty: 'Aumentar cantidad de {name}',
  quantityA11y: 'Cantidad {count}',
  cartEmpty: 'Tu carrito está vacío',
  cartEmptyHint: 'Agrega productos de un restaurante para empezar',
  browseRestaurants: 'Ver restaurantes',
  yourLastOrder: 'Tu último pedido',
  deliveredOn: 'Entregado el {date}',
  orderAgain: 'Pedir de nuevo',
  popularRightNow: 'Populares ahora',
  popularRightNowHint: 'Lo más pedido este mes',
  popularItemA11y: '{name} de {restaurant}, {price}',
  ordersCountOne: '{count} pedido',
  ordersCountOther: '{count} pedidos',
  someItemsUnavailable: 'Algunos productos no están disponibles',
  notAdded: 'No se agregaron: {items}',
  reorderFailed: 'No se pudo repetir el pedido',
  orderSummary: 'RESUMEN DEL PEDIDO',
  subtotal: 'Subtotal',
  deliveryFee: 'Costo de envío',
  taxesFees: 'Impuestos y cargos',
  total: 'Total',
  checkoutWithTotal: 'Finalizar pedido, total {total}',
  ok: 'Aceptar',
  viewOrder: 'Ver pedido',
  orderNotPlacedCartRestored: 'Tu pedido no se realizó y tu carrito se restauró.',
  orderNotUndone: 'No se pudo deshacer el pedido #{number}.',
  paymentSuccessful: 'Pago realizado',
  paymentSuccessfulMessage: 'Pedido #{number} confirmado y pagado con Safepay.',
  paymentPending: 'Pago pendiente',
  paymentPendingMessage: 'Se realizó el pedido #{number}. Confirmaremos el pago en breve.',
  paymentCancelled: 'Pago cancelado',
  paymentCancelledMessage: 'Cancelaste el pago.',
  paymentFailed: 'Pago fallido',
  paymentFailedReason: 'Safepay informó: {reason}.',
  paymentFailedMessage: 'Tu pago no se completó.',
  orderPlaced: '¡Pedido realizado!',
  orderPlacedCashMessage: 'Tu pedido #{number} fue realizado. Paga al repartidor al recibirlo.',
  placeOrderFailed: 'No se pudo realizar el pedido',
  checkoutFailed: 'No se pudo completar el pedido',

  // Saved addresses
  savedAddresses: 'Direcciones guardadas',
  addNewAddress: 'Añadir nueva dirección',
  editAddress: 'Editar dirección',
  addressLabel: 'Nombre',
  labelHome: 'Casa',
  labelWork: 'Trabajo',
  labelOther: 'Otro',
  customLabelPlaceholder: 'Nombra este lugar (p. ej. Gimnasio)',
  deliveryInstructions: 'Instrucciones de entrega (opcional)',
  setAsDefault: 'Usar como dirección predeterminada',
  defaultBadge: 'Predeterminada',
  makeDefault: 'Hacer predeterminada',
  editAction: 'Editar',
  deleteAction: 'Eliminar',
  deleteAddressTitle: 'Eliminar dirección',
  deleteAddressConfirm: '¿Quitar "{label}" de tus direcciones guardadas?',
  noSavedAddresses: 'Aún no hay direcciones guardadas',
  noSavedAddressesHint: 'Guarda tu casa o trabajo y pagar será cuestión de un toque.',
  addDeliveryAddress: 'Añadir dirección de entrega',
  chooseDeliveryAddress: 'Elegir dirección de entrega',
  manageAddresses: 'Gestionar direcciones',
  saveToMyAddresses: 'Guardar en mis direcciones',
  useSavedAddress: 'Usar una dirección guardada',
  addressSaveFailed: 'No se pudo guardar la dirección',

  // Checkout
  checkout: 'Finalizar pedido',
  closeCheckout: 'Cerrar pago',
  validation: 'Faltan datos',
  fillDeliveryAddress: 'Completa la dirección de entrega',
  deliveryAddress: 'Dirección de entrega',
  streetAddress: 'Calle y número',
  city: 'Ciudad',
  zipCode: 'Código postal',
  paymentMethod: 'Método de pago',
  payWithSafepay: 'Pagar con Safepay',
  payWithSafepayHint: 'Tarjeta / billetera — pago en línea seguro',
  cashOnDelivery: 'Pago contra entrega',
  cashOnDeliveryHint: 'Paga en efectivo al repartidor al llegar',
  deliveryNotes: 'Notas de entrega',
  deliveryNotesPlaceholder: 'Indicaciones para el repartidor (p. ej., código de acceso, piso…)',
  placeOrder: 'Realizar pedido',
  placingOrder: 'Realizando pedido…',
  safepaySecureNote: 'Safepay procesa de forma segura los pagos con tarjeta y billetera',

  // Order status
  orderStatusTitle: 'Estado del pedido',
  loadingOrder: 'Cargando tu pedido…',
  loadOrderFailed: 'No se pudo cargar el estado del pedido',
  estArrival: 'Llegada estimada {time}',
  phasePlaced: 'Pedido realizado',
  phaseOnTheWay: 'En camino',
  inProgress: 'En curso…',
  orderCancelledTitle: 'Pedido cancelado',
  orderCancelledHint: 'Este pedido fue cancelado. Si no lo esperabas, contacta a soporte.',
  thanksForReview: 'Gracias por tu reseña',
  rateYourOrder: 'Califica tu pedido',
  continueShopping: 'Seguir comprando',
  viewAllOrders: 'Ver todos los pedidos',
  statusPending: 'Pendiente',
  statusConfirmed: 'Confirmado',
  statusPreparing: 'En preparación',
  statusReady: 'Listo',
  statusPickedUp: 'Recogido',
  statusOutForDelivery: 'En reparto',
  statusDelivered: 'Entregado',
  statusCancelled: 'Cancelado',

  // Order history
  loadOrdersFailed: 'No se pudieron cargar los pedidos',
  noOrdersYet: 'Aún no tienes pedidos',
  noOrdersHint: 'Tus pedidos anteriores aparecerán aquí.',
  moreItemsOne: '+{count} más',
  moreItemsOther: '+{count} más',
  restaurantFallback: 'Restaurante',
  reviewed: 'Calificado',
  rate: 'Calificar',

  // Restaurant menu
  loadRestaurantFailed: 'No se pudieron cargar los datos del restaurante',
  addToCartFailed: 'No se pudo agregar al carrito',
  restaurantNotFound: 'Restaurante no encontrado',
  premiumDelivery: 'ENTREGA PREMIUM',
  free: 'Gratis',
  closed: 'Cerrado',
  premiumBadge: 'PREMIUM',
  minOrder: 'Mín. {amount}',
  ratingA11yOne: 'Calificación de {rating} de 5 según {count} reseña',
  ratingA11yOther: 'Calificación de {rating} de 5 según {count} reseñas',
  tagVeg: 'VEG',
  tagVegan: 'VEGANO',
  tagGlutenFree: 'SIN GLUTEN',
  addToCart: 'Agregar',
  unavailable: 'No disponible',
  noMenuItems: 'No hay platos disponibles',
  viewCart: 'VER CARRITO',
  viewCartA11yOne: 'Ver carrito, {count} producto',
  viewCartA11yOther: 'Ver carrito, {count} productos',

  // Review
  reviewNotSaved: 'Reseña no guardada',
  pleaseRefresh: 'Actualiza la pantalla.',
  reviewSubmitFailed: 'No se pudo enviar la reseña',
  pleaseTryAgain: 'Inténtalo de nuevo.',
  reviewCommentPlaceholder: '¿Qué te pareció? (opcional)',
  commentFor: 'Comentario sobre {name}',
  addComment: 'Agregar comentario',
  yourRiderNamed: 'Tu repartidor, {name}',
  yourRider: 'Tu repartidor',
  reviewDeliveryLabel: 'ENTREGA',
  reviewsFinal: 'Las reseñas no se pueden editar después de enviarlas.',
  rateMoreOne: 'Califica {count} más para enviar',
  rateMoreOther: 'Califica {count} más para enviar',
  submitReview: 'Enviar reseña',
};

const fr: Strings = {
  cancel: 'Annuler',
  save: 'Enregistrer',
  close: 'Fermer',
  back: 'Retour',
  retry: 'Réessayer',
  error: 'Erreur',

  preferences: 'PRÉFÉRENCES',
  darkMode: 'Mode sombre',
  darkModeHint: 'Plus reposant en faible luminosité',
  notificationSettings: 'Notifications',
  notificationSettingsHintOn: 'Suivi des commandes activé',
  notificationSettingsHintOff: 'Notifications désactivées',
  language: 'Langue',
  legalAbout: 'MENTIONS LÉGALES',
  privacyPolicy: 'Politique de confidentialité',
  termsOfService: "Conditions d'utilisation",
  appVersion: "Version de l'app",
  logOut: 'Se déconnecter',
  loggedInAs: 'Connecté en tant que {email}',

  chooseLanguage: 'Choisir la langue',
  languageSheetHint:
    'Les menus, boutons et notifications de commande utiliseront cette langue. Les noms des restaurants et des plats restent tels que le restaurant les a écrits.',
  languageSaveFailed: "Impossible d'enregistrer votre langue sur le serveur. Elle reste utilisée sur cet appareil.",

  notificationsTitle: 'Notifications',
  pushNotifications: 'Notifications push',
  pushNotificationsHint: "Autoriser Foodie à envoyer des notifications sur cet appareil",
  orderUpdates: 'Suivi de commande',
  orderUpdatesHint: 'Confirmée, en préparation, en route et livrée',
  promotions: 'Offres et promotions',
  promotionsHint: 'Réductions des restaurants que vous aimez',
  notificationsBlocked:
    'Les notifications de Foodie sont désactivées dans les réglages du téléphone, rien ne peut donc être affiché.',
  openSettings: 'Ouvrir les réglages',
  notificationsSaveFailed: "Impossible d'enregistrer ce changement. Vérifiez votre connexion et réessayez.",
  notificationsSaved: 'Les modifications sont enregistrées automatiquement.',

  // Tabs
  tabExplore: 'Explorer',
  tabSearch: 'Rechercher',
  tabCart: 'Panier',
  tabProfile: 'Profil',

  // Home
  deliverTo: 'Livrer à',
  goodMorning: 'Bonjour',
  goodAfternoon: 'Bon après-midi',
  goodEvening: 'Bonsoir',
  homeSearchPlaceholder: 'Sushis, pâtes ou burgers…',
  categories: 'Catégories',
  viewAll: 'Tout voir',
  categoryAll: 'Tout',
  popularNearYou: 'Populaires près de chez vous',
  allRestaurants: 'Tous les restaurants',
  placesOne: '{count} établissement',
  placesOther: '{count} établissements',
  noRestaurantsFound: 'Aucun restaurant trouvé',
  yourOrder: 'Votre commande',
  orderHeadlinePending: 'En attente du restaurant',
  orderHeadlineConfirmed: 'Commande confirmée',
  orderHeadlinePreparing: 'Commande en préparation',
  orderHeadlineReady: 'Votre repas est prêt',
  orderHeadlinePickedUp: 'Le livreur a récupéré votre commande',
  orderHeadlineOutForDelivery: 'En route vers vous',
  tapForDetails: 'Touchez pour voir le détail',
  enjoyYourMeal: 'Bon appétit !',
  arrivingAround: 'Arrivée ~{time}',
  riderDelivering: '{name} livre votre commande',
  openOrderA11y: '{headline}, {restaurant}. Ouvrir la commande',
  dismissOrderUpdate: 'Masquer le suivi',
  trackOrder: 'Suivre',
  moreOrdersOne: '+{count} autre commande',
  moreOrdersOther: '+{count} autres commandes',
  moreOrdersA11yOne: '{count} autre commande. Ouvrir l’historique',
  moreOrdersA11yOther: '{count} autres commandes. Ouvrir l’historique',

  // Search
  searchPlaceholder: 'Restaurants, courses…',
  searching: 'Recherche…',
  noResults: 'Aucun résultat',
  noResultsHint: 'Essayez un autre terme',
  popularCuisines: 'Cuisines populaires',
  recentSearches: 'Recherches récentes',
  popularSearches: 'Recherches populaires',
  searchResults: 'Résultats ({count})',
  freeDelivery: 'Livraison gratuite',
  minutesShort: '{count} min',

  // Profile
  profileTabPersonal: 'Personnel',
  profileTabBusiness: 'Pro',
  profileTabSettings: 'Réglages',
  logOutConfirm: 'Voulez-vous vraiment vous déconnecter ?',

  // Profile › Personal
  guestUser: 'Invité',
  premiumMember: 'MEMBRE PREMIUM',
  personalInformation: 'Informations personnelles',
  orderHistory: 'Historique des commandes',
  paymentMethods: 'Moyens de paiement',
  loyaltyPoints: 'Points fidélité',
  pointsCount: '{count} pts',
  loyaltyHint: 'Gagnez des points à chaque commande',

  // Profile › Business
  yourPath: 'Votre parcours',
  yourPathHint: 'Choisissez comment collaborer avec le monde culinaire.',
  partnerTier: 'PARTENAIRE',
  restaurantOwner: 'Restaurateur',
  restaurantOwnerHint: 'Touchez des milliers de clients affamés et développez votre cuisine grâce à notre réseau logistique professionnel.',
  registerStore: 'Inscrire mon restaurant',
  alreadyRegistered: 'Déjà inscrit ? Se connecter →',
  flexibleWork: 'TRAVAIL FLEXIBLE',
  deliveryDriver: 'Livreur',
  deliveryDriverHint: 'Soyez votre propre patron. Gagnez une rémunération attractive en livrant le meilleur de la gastronomie de votre ville.',
  becomeRider: 'Devenir livreur',
  alreadyRider: 'Déjà livreur ? Se connecter →',
  weeklyPayouts: 'Paiements hebdomadaires',
  weeklyPayoutsHint: 'Virement direct chaque lundi matin.',
  support247: 'Assistance 24h/24',
  support247Hint: 'Aide prioritaire pour les partenaires.',

  // Cart
  removeItem: "Retirer l'article",
  removeItemConfirm: 'Retirer {name} du panier ?',
  remove: 'Retirer',
  clearCart: 'Vider le panier',
  clearCartConfirm: 'Retirer tous les articles ?',
  clear: 'Vider',
  yourCart: 'Votre panier',
  cartFrom: 'de {restaurant}',
  itemsOne: '{count} article',
  itemsOther: '{count} articles',
  removeNamed: 'Retirer {name}',
  priceEach: '{price} l’unité',
  decreaseQty: 'Diminuer la quantité de {name}',
  increaseQty: 'Augmenter la quantité de {name}',
  quantityA11y: 'Quantité {count}',
  cartEmpty: 'Votre panier est vide',
  cartEmptyHint: "Ajoutez des articles d'un restaurant pour commencer",
  browseRestaurants: 'Voir les restaurants',
  yourLastOrder: 'Votre dernière commande',
  deliveredOn: 'Livrée le {date}',
  orderAgain: 'Commander à nouveau',
  popularRightNow: 'Populaire en ce moment',
  popularRightNowHint: 'Les plus commandés ce mois-ci',
  popularItemA11y: '{name} de {restaurant}, {price}',
  ordersCountOne: '{count} commande',
  ordersCountOther: '{count} commandes',
  someItemsUnavailable: 'Certains articles sont indisponibles',
  notAdded: 'Non ajoutés : {items}',
  reorderFailed: 'Impossible de recommander',
  orderSummary: 'RÉCAPITULATIF',
  subtotal: 'Sous-total',
  deliveryFee: 'Frais de livraison',
  taxesFees: 'Taxes et frais',
  total: 'Total',
  checkoutWithTotal: 'Paiement, total {total}',
  ok: 'OK',
  viewOrder: 'Voir la commande',
  orderNotPlacedCartRestored: "Votre commande n'a pas été passée et votre panier a été restauré.",
  orderNotUndone: "La commande #{number} n'a pas pu être annulée.",
  paymentSuccessful: 'Paiement réussi',
  paymentSuccessfulMessage: 'Commande #{number} confirmée et payée via Safepay.',
  paymentPending: 'Paiement en attente',
  paymentPendingMessage: 'La commande #{number} a été passée. Nous confirmerons le paiement sous peu.',
  paymentCancelled: 'Paiement annulé',
  paymentCancelledMessage: 'Vous avez annulé le paiement.',
  paymentFailed: 'Échec du paiement',
  paymentFailedReason: 'Safepay a signalé : {reason}.',
  paymentFailedMessage: "Votre paiement n'a pas abouti.",
  orderPlaced: 'Commande passée !',
  orderPlacedCashMessage: 'Votre commande #{number} a été passée. Payez le livreur à la livraison.',
  placeOrderFailed: 'Impossible de passer la commande',
  checkoutFailed: 'Échec de la commande',

  // Saved addresses
  savedAddresses: 'Adresses enregistrées',
  addNewAddress: 'Ajouter une adresse',
  editAddress: "Modifier l'adresse",
  addressLabel: 'Nom',
  labelHome: 'Maison',
  labelWork: 'Travail',
  labelOther: 'Autre',
  customLabelPlaceholder: 'Nommez ce lieu (ex. Salle de sport)',
  deliveryInstructions: 'Instructions de livraison (facultatif)',
  setAsDefault: 'Définir comme adresse par défaut',
  defaultBadge: 'Par défaut',
  makeDefault: 'Définir par défaut',
  editAction: 'Modifier',
  deleteAction: 'Supprimer',
  deleteAddressTitle: "Supprimer l'adresse",
  deleteAddressConfirm: 'Retirer « {label} » de vos adresses enregistrées ?',
  noSavedAddresses: 'Aucune adresse enregistrée',
  noSavedAddressesHint: 'Enregistrez votre domicile ou bureau et payez en un geste.',
  addDeliveryAddress: 'Ajouter une adresse de livraison',
  chooseDeliveryAddress: "Choisir l'adresse de livraison",
  manageAddresses: 'Gérer les adresses',
  saveToMyAddresses: 'Enregistrer dans mes adresses',
  useSavedAddress: 'Utiliser une adresse enregistrée',
  addressSaveFailed: "Impossible d'enregistrer l'adresse",

  // Checkout
  checkout: 'Paiement',
  closeCheckout: 'Fermer le paiement',
  validation: 'Informations manquantes',
  fillDeliveryAddress: "Veuillez renseigner l'adresse de livraison",
  deliveryAddress: 'Adresse de livraison',
  streetAddress: 'Adresse',
  city: 'Ville',
  zipCode: 'Code postal',
  paymentMethod: 'Moyen de paiement',
  payWithSafepay: 'Payer avec Safepay',
  payWithSafepayHint: 'Carte / portefeuille — paiement en ligne sécurisé',
  cashOnDelivery: 'Paiement à la livraison',
  cashOnDeliveryHint: 'Payez le livreur en espèces à son arrivée',
  deliveryNotes: 'Instructions de livraison',
  deliveryNotesPlaceholder: 'Instructions pour le livreur (ex. : digicode, étage…)',
  placeOrder: 'Commander',
  placingOrder: 'Commande en cours…',
  safepaySecureNote: 'Les paiements par carte et portefeuille sont sécurisés par Safepay',

  // Order status
  orderStatusTitle: 'Suivi de commande',
  loadingOrder: 'Chargement de votre commande…',
  loadOrderFailed: 'Impossible de charger le suivi de commande',
  estArrival: 'Arrivée prévue {time}',
  phasePlaced: 'Commande passée',
  phaseOnTheWay: 'En route',
  inProgress: 'En cours…',
  orderCancelledTitle: 'Commande annulée',
  orderCancelledHint: "Cette commande a été annulée. Si ce n'était pas prévu, contactez l'assistance.",
  thanksForReview: 'Merci pour votre avis',
  rateYourOrder: 'Notez votre commande',
  continueShopping: 'Continuer mes achats',
  viewAllOrders: 'Voir toutes les commandes',
  statusPending: 'En attente',
  statusConfirmed: 'Confirmée',
  statusPreparing: 'En préparation',
  statusReady: 'Prête',
  statusPickedUp: 'Récupérée',
  statusOutForDelivery: 'En livraison',
  statusDelivered: 'Livrée',
  statusCancelled: 'Annulée',

  // Order history
  loadOrdersFailed: 'Impossible de charger les commandes',
  noOrdersYet: 'Aucune commande pour le moment',
  noOrdersHint: 'Vos commandes passées apparaîtront ici.',
  moreItemsOne: '+{count} autre',
  moreItemsOther: '+{count} autres',
  restaurantFallback: 'Restaurant',
  reviewed: 'Noté',
  rate: 'Noter',

  // Restaurant menu
  loadRestaurantFailed: 'Impossible de charger le restaurant',
  addToCartFailed: "Impossible d'ajouter au panier",
  restaurantNotFound: 'Restaurant introuvable',
  premiumDelivery: 'LIVRAISON PREMIUM',
  free: 'Gratuit',
  closed: 'Fermé',
  premiumBadge: 'PREMIUM',
  minOrder: 'Min. {amount}',
  ratingA11yOne: 'Noté {rating} sur 5 ({count} avis)',
  ratingA11yOther: 'Noté {rating} sur 5 ({count} avis)',
  tagVeg: 'VÉGÉ',
  tagVegan: 'VÉGAN',
  tagGlutenFree: 'SANS GLUTEN',
  addToCart: 'Ajouter',
  unavailable: 'Indisponible',
  noMenuItems: 'Aucun plat disponible',
  viewCart: 'VOIR LE PANIER',
  viewCartA11yOne: 'Voir le panier, {count} article',
  viewCartA11yOther: 'Voir le panier, {count} articles',

  // Review
  reviewNotSaved: 'Avis non enregistré',
  pleaseRefresh: 'Veuillez actualiser.',
  reviewSubmitFailed: "Impossible d'envoyer l'avis",
  pleaseTryAgain: 'Veuillez réessayer.',
  reviewCommentPlaceholder: "Qu'en avez-vous pensé ? (facultatif)",
  commentFor: 'Commentaire sur {name}',
  addComment: 'Ajouter un commentaire',
  yourRiderNamed: 'Votre livreur, {name}',
  yourRider: 'Votre livreur',
  reviewDeliveryLabel: 'LIVRAISON',
  reviewsFinal: 'Les avis ne sont plus modifiables après envoi.',
  rateMoreOne: 'Encore {count} note pour envoyer',
  rateMoreOther: 'Encore {count} notes pour envoyer',
  submitReview: "Envoyer l'avis",
};

const STR: Record<CustomerLanguage, Strings> = { en, ur, es, fr };

export function customerT(
  language: CustomerLanguage,
  key: CustomerStringKey,
  params?: Record<string, string | number>,
): string {
  const template = STR[language]?.[key] ?? en[key];
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (match, name) =>
    name in params ? String(params[name]) : match,
  );
}

const ORDER_STATUS_KEYS: Record<string, CustomerStringKey> = {
  Pending: 'statusPending',
  Confirmed: 'statusConfirmed',
  Preparing: 'statusPreparing',
  Ready: 'statusReady',
  PickedUp: 'statusPickedUp',
  OutForDelivery: 'statusOutForDelivery',
  Delivered: 'statusDelivered',
  Cancelled: 'statusCancelled',
};

/** String key for a backend order status (e.g. 'OutForDelivery'), or undefined if unknown. */
export function orderStatusKey(status: string): CustomerStringKey | undefined {
  return ORDER_STATUS_KEYS[status];
}
